### ISSUE TITLE
Make a complete, re-usable boiler-generator association table.

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#107]
We can create a re-usable and complete (or at least, as good as it gets) boiler generator association table that we use instead of the EIA860 table -- using inter-year information where it's available.  Will be useful going forward.  Most of this work has been done in the MCOE work for CPI... but needs to be integrated into one thing.

**Comment by cmgosnell** [comment]
We currently have a temporary function which generates a complete bga, although we'd like to move this into the ingest process as a data table.

Because it relies on data in the database, several things need to happen before that:
- We need a table for each of the entities (plants, generators, boilers, utilities). We need to use these table to compile information about these entities to normalize the rest of the eia tables.
- In order to do that, we need to break the ingest functions into two steps. The first step in that process will be to create the cleaned dataframes for all of the tables, then it can be used to create dataframes for these entity, which can be used to create a dataframe of a new bga, then all of the dataframes can be dumped into data tables.

**Comment by zaneselvans** [comment]
The mcoe.boiler_generator_association() function is looooooong, but now does a good job of creating boiler-generator associations, by creating unit_ids based on the full list of historically associated boilers and generators, using a simple network analysis.  This function can hopefully be adapted pretty directly to the ingest process, and the addition of a unit_id to the boiler and generator entity tables, allowing them to be joined simply when needed.

**Comment by cmgosnell** [comment]
whoop! finally done. bga is a table and there is no longer a bga function in mcoe.py
