### ISSUE TITLE
epacems_to_parquet fails on fast ETL pipeline

### ISSUE THREAD

**Issue by kevinsung** [catalyst-cooperative/pudl#1121]
### Describe the bug
Running the fast ETL pipeline according to the [instructions](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/run_the_etl.html) results in an error because it tries to access a file that has not been downloaded.

### Bug Severity
How badly is this bug affecting you?
 - **Medium:** With some effort, I can work around the bug.

### To Reproduce
- Follow the [instructions](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/dev_setup.html) to set up a development environment
- Follow the [instructions](https://catalystcoop-pudl.readthedocs.io/en/latest/dev/run_the_etl.html#the-fast-etl) to run the fast ETL
- When executing the last step, `epacems_to_parquet datapkg/pudl-fast/epacems-eia/datapackage.json`, get the following error:
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pudl-dev/bin/epacems_to_parquet", line 33, in <module>
    sys.exit(load_entry_point('catalystcoop.pudl', 'console_scripts', 'epacems_to_parquet')())
  File "/home/kjs/projects/pudl/src/pudl/convert/epacems_to_parquet.py", line 313, in main
    epacems_to_parquet(datapkg_path=pathlib.Path(args.datapkg),
  File "/home/kjs/projects/pudl/src/pudl/convert/epacems_to_parquet.py", line 195, in epacems_to_parquet
    raise FileNotFoundError(f"EPA CEMS file not found: {newpath}")
FileNotFoundError: EPA CEMS file not found: datapkg/pudl-fast/epacems-eia/data/hourly_emissions_epacems_1995_al.csv.gz
```

### Expected behavior
The pipeline should run with no errors

### Software Environment?
 - OS: Arch Linux
 - PostgreSQL version: 13.3
 - Python version 3.9.6
 - How did you install PUDL? I cloned the git repository and used conda.

**Comment by zaneselvans** [comment]
Hmm. That's a file which *would* have been created by your running the ETL, if you included the EPA CEMS data from 1995, but the fast ETL just does the last year of data, so that one wouldn't be there.  I wonder why the script is looking for that year of data.  If you look in the data package directory, there should probably just be the 2019 EPA CEMS outputs for (I think) Idaho. If you do something like:
```
epacems_to_parquet --years 2019 --states ID -- datapkg/pudl-fast/epacems-eia/datapackage.json
```
(or whatever the actually existing years and states are in your outputs) then does it work? If so we should either update the script to just try and process the data which is present, or update the instructions to tell folks to specify the same years/states which are processed by the "fast ETL"

**Comment by kevinsung** [comment]
Indeed, the data directory contains just the 2019 data, and running the command you provided works. Either solution you suggested seems reasonable. Another option would be to write the years to process in one of the configuration files associated with the fast ETL.

**Comment by zaneselvans** [comment]
Well, the years/states are already in the configuration files, since the ETL pipeline has to know which ones to process, but the `epacems_to_parquet` script doesn't use those configuration files. It just looks at what's on disk. It should probably just be smarter about that, and only try to convert years / states for which there's actually data.  But we're ditching the intermediate archival format and going to just outputting the Parquet files an database files directly, so maybe not worth too much of a detour to fix.

**Comment by zaneselvans** [comment]
Okay I went ahead and updated the command line args in the docs to specify the right `--years` and `--states` for the time being.
