### ISSUE TITLE
Remove other duplicated metadata from constants.py

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1214]
In addition to the metadata stored in `src/pudl/package_data/meta/datapkg/datapackage.json` there's a bunch of metadata in `constants.py` which is being subsumed within the new `pudl.metadata` module.  We need to remove all of the old duplicate metadata, and update any references to it in the codebase to point at the new metadata structures.

By the time we're done with the metadata migration and harvesting refactor, we should probably have migrated a large portion of the contents of `constants.py` into the metadata or other modules -- many of the codes / labels in there should be turned into ENUM constraints or small tables in the database.

For each of the values below that are stored in the new `pudl.metadata` subpackage:
* Find the old version of that value in `pudl.constants` and remove it,
* Replace all references to the old module with a reference to the new canonical metadata source.

**Comment by ezwelty** [comment]
The `pudl.metadata`  (#806) modules `fields`, `resources`, `constants`, and `labels` subsume a lot of (but perhaps not all) metadata in `src/pudl/package_data/meta/datapkg/datapackage.json` and `pudl.constants`. My advice for the migration:

- Move metadata from the old places to `pudl.metadata only if you are absolutely sure it does not already exist there in some form. Most likely it already exists and you just need to update the code to point to the new location.
- When possible, access metadata via the class API. For example, use `pudl.classes.Source.from_id(id)` (instead of `pudl.constants.SOURCES[id]`) and `pudl.classes.Field.dtype` (instead of `pudl.constants.FIELD_DTYPES`).

Note that I placed the "original-code-to-human-friendly-label" dictionaries in the `pudl.metadata.labels` module. The labels (dictionary values) are used to populate some `field.constraints.enum`. But these dictionaries also need to be accessed directly in the transform step (an example where the class API cannot be used) to replace the codes with their corresponding labels.
