### ISSUE TITLE
Categorizing RMI Projects

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1433]

**Comment by MichaelTiemannOSC** [comment]
My ears are 🔥 burning

**Comment by aesharpe** [comment]
> My ears are 🔥 burning

May I ask what you mean by that? I did accidentally put this in the wrong repo, but our collaboration with RMI is very much public :)

**Comment by MichaelTiemannOSC** [comment]
No worries!  I spent the whole weekend working on RMI's January dataset and sending them many comments.  I wonder whether we are traversing the same territory (emissions_targets in particular).  I very much appreciate the work you all do for them!

I do know that PUDL is the upstream source for much of RMI's data, which I why, separately, I filed this report with PUDL: https://github.com/catalyst-cooperative/pudl/issues/1427.  But I also recently sent them many emails because I'm not aware if they have a public Git repo.  I'm excited to see what's cooking!!

**Comment by aesharpe** [comment]
Ooo, yes! Lots in the pipeline! We have a joint repo with them to process PUDL data called rmi-ferc1-eia, but we also do a lot of processing locally. I don't think RMI has their own public repos yet. Regarding emissions data, we cleaned and published the CEMS hourly dataset which helps with the emissions projections used in the hub! I'll take a look at the issue you posted and see what we can do about it.
