### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#147]
- [x] Travis
- [ ] AppVeyor?
- [x] Divide tests into slow and fast, only run fast on CI
- [x] Get a fancy build status button

**Comment by karldw** [comment]
Some of the tests take a ton of memory, but I'm guessing they won't be in the fast subset.

**Comment by karldw** [comment]
FYI: Travis can [cache](https://docs.travis-ci.com/user/caching/) things for you.

**Comment by zaneselvans** [comment]
I have TravisCI set up and working. Currently, it will run any test marked `ci` and the only test so marked at the moment is a Hello World. Now we need to start creating a suite of tests that can actually be run on Travis and other times when we just want to test our code, and not load the entire universe of data.

**Comment by zaneselvans** [comment]
The Travis CI builds are working. Rather than categorize some tests as fast, I created (at least for now) a separate travis_ci_test.py module, which runs the ETL on a small subset of all the data -- which is downloaded to a local datastore on the Travis VM. Right now it does FERC Form 1 & EIA860 for 2012 and 2016, and EIA923 EPA CEMS for just 2016. In addition, the CEMS only pulls Colorado's data, to minimize the time the whole thing takes to run, disk use, etc.

* What advantages does AppVeyor have?
* Are there better ways to test without requiring more data downloads?

**Comment by karldw** [comment]
Great!  The only advantage of adding AppVeyor would be also testing on Windows.

For the simpler functions, we could add tests with dummy datasets.
