### ISSUE TITLE
pudl-dev setup fails when installing pip dependencies

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#1742]
### Describe the bug
When I try and install the `pudl-dev` environment using miniconda, I get the following error when installing pip dependencies:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['A:\\miniconda3\\envs\\pudl-dev\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'a:\\GitHub\\pudl\\devtools\\condaenv.5feun3q5.requirements.txt']
Pip subprocess output:
Obtaining file:///A:/GitHub/pudl (from -r a:\GitHub\pudl\devtools\condaenv.5feun3q5.requirements.txt (line 1))
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Collecting setuptools<63
        Using cached setuptools-62.6.0-py3-none-any.whl (1.2 MB)
      Collecting pip<23,>=21
        Using cached pip-22.1.2-py3-none-any.whl (2.1 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting setuptools_scm
        Using cached setuptools_scm-7.0.4-py3-none-any.whl (42 kB)
      Collecting packaging>=20.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting typing-extensions
        Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      ERROR: To modify pip, please run the following command:
      A:\miniconda3\envs\pudl-dev\python.exe -m pip install --ignore-installed --no-user --prefix C:\Users\Greg\AppData\Local\Temp\pip-build-env-brs_7b8q\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools<63 pip>=21,<23 wheel setuptools_scm
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed

CondaEnvException: Pip failed
```

### Bug Severity
How badly is this bug affecting you?
 - **High:** This bug is preventing me from using PUDL.

### To Reproduce
I am trying to install `pudl-dev` using from the current `main` branch of pudl (technically I am running from my fork of main, but I ensured that it is up to date with upstream main)

 - I completely removed and reinstalled miniconda using the latest Windows 64bit installer here: https://docs.conda.io/en/latest/miniconda.html#latest-miniconda-installer-links
 - I ran `conda update conda` to update to conda 4.13.0
 - I ran `conda config --set channel_priority strict`
 - I ran
```
cd pudl
conda env create --name pudl-dev --file devtools/environment.yml
```
 - It successfully downloads and installs all of the packages, but then fails when it gets to the pip dependencies

### Expected behavior
I expected the `pudl-dev` environment to be sucessfully set up.

### Software Environment?
 - OS: Windows 10 Enterprise 21H1 build 19043.1766
 - Python version: 3.9.12
 - How did you install PUDL? miniconda

### Additional context
I also ran into this issue originally here when updating my pudl-dev environment: https://github.com/catalyst-cooperative/pudl/pull/1608#issuecomment-1178258122

**Comment by grgmiller** [comment]
The most similar issue to this that I was able to find online was this: https://github.com/pypa/pip/issues/11120

**Comment by zaneselvans** [comment]
Thanks for the pointer on the `pyproject.toml` / `pip` issue. I definitely wasn't aware that `pip` need not be there, and I've removed it and `wheel` and added a `build-backend` and `pip` seems to be happy with this arrangement now, if you want to pull the most recent version of the `allocate_fuel` branch.

### A couple of clarifications:
* You say you're working off of the `main` branch of PUDL, but in your PR it looked like you were merging into the `allocate_fuel` branch (which made sense) and I had merged all the changes in `dev` into `allocate_fuel` before this problem started... which branch is your fork based on?
* You say you're using Python 3.9.12, but the `pudl-dev` environment requires Python 3.10.  Is 3.9.12 just the version of Python in your base conda environment, or are your somehow trying to override the requirement for Python 3.10 in the `pudl-dev` environment? (conda should be able to create an environment with whatever version of Python, regardless of the version in the base environment).

### Some things to try:
* Pull / merge the most recent version of the `allocate_fuel` branch with the revised `pyproject.toml` file.
* Would you be willing to try creating the environment using `mambaforge` instead of `miniconda`? I don't think it should make a difference since the problem is coming up in the `pip` install, and you had strict channel priority enabled and pointing at `conda-forge` but we're using `mambaforge` to manage our conda environment so it would be good to check. You can [download it here](https://github.com/conda-forge/miniforge)
* Are you able to create a non-conda virtual environment and run the pip install of just PUDL within it? To do so you would deactivate your current conda environment and run the following commands from within the top level PUDL repo directory. Note you'll need to give it the path to a Python 3.10 interpreter, but that can be the one that's inside one of your conda environments (this is just for temporary testing). These are bash commands so... whatever the Windows equivalent is I'm not sure:

```
virtualenv --python /path/to/any/python3.10 venv 
source venv/bin/activate
pip install -e "./[doc,test,dev,datasette]" 
```

You should see a bunch of output from `pip` doing the installation, hopefully successfully...

To get out of and remove the virtual environment:

```
deactivate
rm -rf venv
```

If you just want to try revising the pyproject.toml, what I changed was the the build system section:
```toml
[build-system]
requires = [
    "setuptools<63",
    "setuptools_scm",
]
build-backend = "setuptools.build_meta"
```

**Comment by zaneselvans** [comment]
Another note: it's not `conda` trying to create environments for the `pre-commit` hooks. Those environments are managed via `pre-commit` itself, and I think it uses `virtualenv` and `pip` -- creating a separate virtual environment for each hook (since they could in theory have different requirements / dependencies). The package being checked (pudl) is also installed into those environments. It's interesting that it gets through creating *some* of the hook environments and then barfs on `doc8` apparently.

Are you able to directly install `doc8` in a virtual environment using `pip`?

**Comment by grgmiller** [comment]
Thanks, Zane. 

Responses:

> You say you're working off of the main branch of PUDL, but in your PR it looked like you were merging into the allocate_fuel branch (which made sense) and I had merged all the changes in dev into allocate_fuel before this problem started... which branch is your fork based on?

When I first attempted to update the environment, I did it based on the `allocate_fuel` branch in my fork after merging in the upstream changes from `allocate_fuel`. After that failed, I thought maybe that the cause was that the environment/setup files in this branch weren't working, so I thought it would be safer to try and install the environment based on `main` - but obviously that also did not work

> You say you're using Python 3.9.12, but the pudl-dev environment requires Python 3.10. Is 3.9.12 just the version of Python in your base conda environment, or are your somehow trying to override the requirement for Python 3.10 in the pudl-dev environment?

3.9.2 is the version of my base conda environment. The pudl-dev environment installed 3.10.5

I'll attempt some of the fixes you suggested and let you know how it goes.

**Comment by zaneselvans** [comment]
So long as the `allocate_fuel` branch is passing CI, which you can see in the build status on PR #1096 I think we should believe that the upstream environment is working as expected (at least on Linux, which is where the CI runs).

It sounds like @arengel may have run into the same issue recently, and solved it by editing the `pip` requirement in `devtools/environment.yml` to:

```
  - pip>=21,<22
```

But I'm still curious if the changes to the build system requirements in the `pyproject.toml` file might fix all this even with `pip` v22.

**Comment by grgmiller** [comment]
Ok so after merging `upstream/allocate_fuel` into my branch and re-running the environment setup (still using miniconda), the setup now successfully finishes. However, I am running into the same error when I go to do a commit and it sets up the virtual environments for the pre-commit hooks. 

I did install a virtual environment and tried installing doc8 by itself, which worked.

Next I'm going to try editing the pip requirement.

**Comment by grgmiller** [comment]
After editing the environment file to `pip>=21,<22`, I was able to successfully create the environment. However, I'm still getting an error when I go to do a commit, at the same point:
```
[INFO] Installing environment for https://github.com/PyCQA/doc8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Greg\\.cache\\pre-commit\\repovo8ty0b9\\py_env-default\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\greg\.cache\pre-commit\repovo8ty0b9
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'

stderr:
      error: subprocess-exited-with-error

      pip subprocess to install build dependencies did not run successfully.
      exit code: 1

      [20 lines of output]
      Collecting pip>=19.3.1
        Using cached pip-22.1.2-py3-none-any.whl (2.1 MB)
      Collecting setuptools>=42
        Using cached setuptools-63.1.0-py3-none-any.whl (1.2 MB)
      Collecting setuptools_scm[toml]>=3.5.0
        Using cached setuptools_scm-7.0.4-py3-none-any.whl (42 kB)
      Collecting setuptools_scm_git_archive>=1.1
        Using cached setuptools_scm_git_archive-1.4-py2.py3-none-any.whl (3.3 kB)
      Collecting wheel>=0.33.6
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting packaging>=20.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting typing-extensions
        Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      ERROR: To modify pip, please run the following command:
      C:\Users\Greg\.cache\pre-commit\repovo8ty0b9\py_env-default\Scripts\python.EXE -m pip install --ignore-installed --no-user --prefix C:\Users\Greg\AppData\Local\Temp\pip-build-env-ptwpbyma\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- pip >= 19.3.1 setuptools >= 42 setuptools_scm[toml] >= 3.5.0 setuptools_scm_git_archive >= 1.1 wheel >= 0.33.6
      [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error

    pip subprocess to install build dependencies did not run successfully.
    exit code: 1

    See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
```

Looking at `doc8`'s [pyproject file](https://github.com/PyCQA/doc8/blob/main/pyproject.toml), it looks like it still includes pip as well:

```
[build-system]
requires = [
  "pip >= 19.3.1",
  "setuptools >= 42",
  "setuptools_scm[toml] >= 3.5.0",
  "setuptools_scm_git_archive >= 1.1",
  "wheel >= 0.33.6",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
```

I'm wondering if this is the issue and needs to be submitted as an issue to them?

**Comment by zaneselvans** [comment]
Ahhh, yeah I bet that's it.

So it sounds like modifying our build requirements fixed the problem on our side -- that the `pudl-dev` environment creates fine now even with the more recent version of `pip` and the main issue is probably that `doc8` is also exercising the same problem?

I guess for now on your branch just comment out the offending pre-commit hook and we can re-enable it eventually when things get merged in upstream.

**Comment by grgmiller** [comment]
Would I just need to comment out doc8 in `setup.py`, or do you think it will also be necessary to remove from `tox.ini` and `.pre-commit-config.yaml`?

**Comment by zaneselvans** [comment]
I think / hope that you would only need to comment out the doc8 pre-commit hook definition in `.pre-commit-config.yaml` -- it seems to be getting installed just fine when the conda environment is created (which installs the pudl package along with all of its associated dependencies).

Speaking of which what python environment do you have activated when you're trying to install the pre-commit hooks? Is it the `pudl-dev` conda environment? Or the base conda environment? Or just your system python?

**Comment by grgmiller** [comment]
I installed the pre-commit hooks with my `pudl-dev` environment activated. 

Commenting out doc8 from `.pre-commit-config.yaml` seems to have did the trick - everything is working now!

**Comment by arengel** [comment]
Some Hub team members also had issues with pre-commit that produced a similar error message, I was able to fix those issues by adding the setting below to the top of `.pre-commit-config.yaml`, and then conforming the language version for `black` as well (or removing it). I didn't try to figure out what was actually going on but specifying the python version in the pre-commit config got it to work. 

``` yml
default_language_version:
    python: python3.10 # or whatever python version you want
```

I also ran `pre-commit clean` to get rid of all the old pre-commit virtual environments just in case, though not sure that was necessary. I thought maybe the pre-commit python version had to be the same as the one of the environment you install pre-commit from but I don't think that's right since it seems like pre-commit sets up its own virtual environments. 

This [issue](https://github.com/pre-commit/pre-commit/issues/1375) on `pre-commit` addresses something apparently similar though supposedly resolved, which is where I got the idea to see if this setting fixed things, which it has. For now.

**Comment by zaneselvans** [comment]
Okay, it sounds like this issue can be closed now, since the `doc8` problem is out of our control (but hopefully they fix it).. Do you agree @grgmiller?

**Comment by grgmiller** [comment]
Yes, I agree that this can be closed. 

I've created an issue on the `doc8` repo https://github.com/PyCQA/doc8/issues/91, and it sounds like hopefully the original issue that is causing this in `pip` is hopefully going to be fixed as well https://github.com/pypa/pip/issues/11120#issuecomment-1179448615.

For now, running the pre-commit hooks and `tox` will be non-functional for windows users, but maybe I'm the only windows user of pudl who is doing any development, and I currently have a workaround.

**Comment by zaneselvans** [comment]
I think you're the only windows developer who isn't using WSL. I think make it work for `tox` so the CI passes, and if only the expected pre-commit hooks fail when you try to commit, you can re-run the commit with `--no-verify` and it'll bypass the hooks.

**Comment by grgmiller** [comment]
@zaneselvans This has now been fixed in the latest release of doc8 (https://github.com/PyCQA/doc8/releases/tag/v1.0.0) so once pudl updates its doc8 dependency to v1.0 this should hopefully no longer be an issue.

**Comment by zaneselvans** [comment]
Okay, that should happen automatically as soon as the dependabot picks up the version update!
