### ISSUE TITLE
`pudl_out.gens_mega_eia()` fails with start/end date

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1755]
While checking in on the consequences of the database schema changes in #1748 I discovered that the `pudl_out.gens_mega_eia()` method fails when the output object has start/end dates restricting what data is selected and processed. For example this will generate an error:

```py
pudl_out = PudlTabl(
    pudl_engine=pudl_engine,
    start_date="2020-01-01",
    end_date="2020-12-31",
    freq="AS",
    fill_fuel_cost=True,
    roll_fuel_cost=True,
    fill_net_gen=True,
)
pudl_out.gens_mega_eia()
```

The error which comes up says that `technology_description` is missing in one of the dataframes being merged (in a merge that uses that field as a merge key).

**Comment by katie-lamb** [comment]
Update: the issue seems to be more confusing than we initially thought. With a new DB generated from `dev` I was unable to recreate the error and successfully generated `gens_mega` with a bunch of different start and end dates. @zaneselvans can generate `gens_mega` starting from scratch on `dev`, but when attempting to run `pudl_out.plant_parts_eia()` after having run `pudl_out.gens_mega()`, it fails. But when `pudl_out.plant_parts_eia()` is run without running `gens_mega()` first, it works.  

I'm going to try some more experiments and document when the error is generated.

**Comment by zaneselvans** [comment]
@katie-lamb Should this issue be closed now?
