### ISSUE TITLE
Figure out how/when to integrate epacamd-eia crosswalk

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#1758]
Extension of Issue #178

Right now the EPA-EIA crosswalk file is only loaded into the pudl db if the EIA data is also getting loaded into the db. This is because the crosswalk depends on EIA for foreign key validation.

The CEMS data also relies on the crosswalk data for access to accurate `plant_id_eia` values. The values we previously called `plant_id_eia` in the CEMS data are actually EPA's estimated ORISPL codes. The crosswalk connects these plant-level estimates to the actual EIA codes via a `plant_id_epa, unit_id_epa` to `plant_id_eia` map. Most of the plant IDs are identical across EPA and EIA, but a few are not. 

We currently rely on the `plant_id_eia` field in CEMS fix some of the date entries. The `fix_up_dates()` function in the epacems transform module uses the `plant_id_eia` field to map to another dataframe with `plant_id_eia` and `timezone` fields. 

If we want to use this mapping function accurately, we should merge the crosswalk into the CEMS data first. Merging the crosswalk with CEMS in the transform step is all well and good except that it would now require users that just want to work with CEMS data to also download the EIA data (because the CEMS needs the crosswalk which needs EIA).

How do folks feel about this?

**Comment by zaneselvans** [comment]
Some questions:

* What does "EPA's estimated ORISPL codes" mean.  Are they correcting errors? Is there ambiguity in the ORISPL codes? Do they legit change over time and that change isn't captured in the EIA / EPA data? The `plant_id_eia` values should also be valid ORISPL codes. Do we understand what's going on here?
* What do you mean by "fix some of the date entries" -- is that something other than converting the timestamps to UTC and adding the code for the timezone they're located in? I thought that was the only change we were making.
* Are we failing to appropriately set the timezones in the EPA CEMS data because of the mismatch between the `plant_id_eia` and the `plant_id_epa` values?  We also have a little hand compiled set of plant IDs and their attendant timezones which gets used, down under `package_data` -- this was necessary because the CEMS data goes back to 1995 and there are some plants which don't show up in the EIA data that only goes back to 2001.
* If the only implication here is that we're using one ORISPL vs another to determine the timezone, do we think this will actually have a material impact? Or will both IDs associated with a given plant always be in the same timezone?
* Can you describe in more detail what you mean by the scenario in which users "just want to work with CEMS data"?  If they're pulling down the parquet data that we publish it would be up to us what columns / values we put in there.  That being said, the CEMS data is going to be a lot more useful with the other EIA attributes related to the plants & generators & utilities.
* I think it's reasonable to assume / require that someone have access to the whole suite of data that we're publishing to make the best use of the individual components.  The CEMS data is stored in another format because of its size and shape, not because it's intended for use as a standalone dataset.

Given the fact that we're setting an expectation that we will centralize the ETL / data processing and that users will not be running the ETL unless they're doing development work, I don't think it's important that we condition the loading of the glue tables on the datasets they glue together being loaded. In practice we're always going to load all of these data in production and users working with our outputs will have access to all of them.

**Comment by aesharpe** [comment]
> What does "EPA's estimated ORISPL codes" mean. Are they correcting errors? Is there ambiguity in the ORISPL codes? Do they legit change over time and that change isn't captured in the EIA / EPA data? The plant_id_eia values should also be valid ORISPL codes. Do we understand what's going on here?

The raw crosswalk has a field called `CAMD_PLANT_ID` which it describes as _"The unique ID (also known as ORIS code/ORISPL code) of the facility in CAMD's data. (CAMD key)"_. The CEMS data has a field called `ORISPL_CODE` which I assume `CAMD_PLANT_ID` is referring to. Most of the time, these fields are exactly the same. However, there are a few instances (23 plant IDs) where a subset of EIA generators will have a different plant id. Here's an example: 

![Screen Shot 2022-07-15 at 12.58.18 PM.png](https://images.zenhubusercontent.com/5e84c333ad36eafe6787e5b9/b2dc85fb-6123-451b-9453-b2058e112b05)

This is knows to the crosswalk makers and intentionally integrated into their methodology. Here's a snipit from their README: 

_"In rare instances, the Plant IDs do not match between CAMD and EIA's databases. These discrepancies were discovered through the production of eGRID and are regularly tracked and updated with new eGRID releases. In the crosswalk R script, these discrepancies are accounted for before any matching occurs–EIA's plant ID is modified ("MOD_EIA_PLANT_ID") to match CAMD's plant ID and includes a field indicating that the plant ID has been changed ("PLANT_ID_CHANGE_FLAG")."_

**Comment by aesharpe** [comment]
> What do you mean by "fix some of the date entries" -- is that something other than converting the timestamps to UTC and adding the code for the timezone they're located in? I thought that was the only change we were making.

This is just the existing UTC conversion and timezone code.

**Comment by aesharpe** [comment]
> Are we failing to appropriately set the timezones in the EPA CEMS data because of the mismatch between the plant_id_eia and the plant_id_epa values? We also have a little hand compiled set of plant IDs and their attendant timezones which gets used, down under package_data -- this was necessary because the CEMS data goes back to 1995 and there are some plants which don't show up in the EIA data that only goes back to 2001.

My guess is that it will not impact the timezones at all seeing as a) there are only a handful of miss-matched plant ids and b) they are sub-plant (see example above where a few of the generators have a different plant id) meaning they are probably located at the same place.

I can quickly check the EIA data to make sure all the plant discrepancies fall within the same timezone.

**Comment by aesharpe** [comment]
> Can you describe in more detail what you mean by the scenario in which users "just want to work with CEMS data"? If they're pulling down the parquet data that we publish it would be up to us what columns / values we put in there. That being said, the CEMS data is going to be a lot more useful with the other EIA attributes related to the plants & generators & utilities.

I suppose now that we are moving towards a data catalog this doesn't matter as much. I was envisioning a scenario where someone wanted run the ETL for CEMS only, but that will probably never happen. Also, to run the`epacems_to_parquet` script you need a pudl db with EIA data anyways.

**Comment by aesharpe** [comment]
> Given the fact that we're setting an expectation that we will centralize the ETL / data processing and that users will not be running the ETL unless they're doing development work, I don't think it's important that we condition the loading of the glue tables on the datasets they glue together being loaded. In practice we're always going to load all of these data in production and users working with our outputs will have access to all of them.

Great, this seems reasonable!

**Comment by zaneselvans** [comment]
Okay, so we don't know where the discrepancies between the `plant_id_eia` values in the EIA 860/923 (which are also ORISPL codes) and the `plant_id_epa` reported in the CEMS data are, and the crosswalk is designed to bridge between the two.  Do we believe that neither of the sets of IDs is "correct" and that we will have to manage the discrepancies between the two datasets in analyses basically forever? I.e. we have to keep the discrepancies intact, and translate between them rather than adopting one or the other as the canonical definition and applying it everywhere?

Why is the `plant_id_epa` assumed the be the "approximate" (i.e. less accurate) value?

So if we were going to use the location associated with `plant_id_eia` for timezone determination, then in the CEMS ETL we would need to join the `plant_id_eia` column to CEMS first, using the crosswalk mapping to `plant_id_epa` and then look up each plant's timezone based on the `plant_id_eia` rather than `plant_id_epa`? And then presumably drop the `plant_id_eia` column before output? Or do we feel like we need to retain that column for easier joining in the future with EIA data?

I can see how that would be more correct, but anything we do with CEMS has to be done a billion times, and anything we store in CEMS has to be stored a billion times. If it's only for the sake of getting the timezone right, I have to imagine that the ORISPL IDs that are in the CEMS data are all going to show up as having the same timezones as their `plant_id_eia` counterparts.

> I was envisioning a scenario where someone wanted run the ETL for CEMS only.

Ah yeah, this is already not allowed. If you try and run the ETL for EPA CEMS alone it will force you to pull in the EIA data to get the plant attributes so it can convert to UTC and add the timezone codes.

**Comment by aesharpe** [comment]
> Do we believe that neither of the sets of IDs is "correct" and that we will have to manage the discrepancies between the two datasets in analyses basically forever? I.e. we have to keep the discrepancies intact, and translate between them rather than adopting one or the other as the canonical definition and applying it everywhere?

> Why is the plant_id_epa assumed the be the "approximate" (i.e. less accurate) value?

This is a good question. I think I was calling `plant_id_epa` less accurate because the `plant_id_eia` value seems to add more granularity to the data. See above where `plant_id_epa` says 562 across the board and `plant_id_eia` adds in 57068. I wonder if these instances are similar to the times where we had combined several `plant_id_eia` values into one `plant_id_pudl`. 

Ideally we would just have one correct set of ORISL IDs and not "eia" and "epa" versions.

**Comment by aesharpe** [comment]
> So if we were going to use the location associated with plant_id_eia for timezone determination, then in the CEMS ETL we would need to join the plant_id_eia column to CEMS first, using the crosswalk mapping to plant_id_epa and then look up each plant's timezone based on the plant_id_eia rather than plant_id_epa? And then presumably drop the plant_id_eia column before output? Or do we feel like we need to retain that column for easier joining in the future with EIA data?

I am tempted to drop `plant_id_epa` and just call `plant_id_eia` the "correct" ORISPL code. But I'm tempted to talk to someone at EIA/EPA about this...

**Comment by aesharpe** [comment]
> I have to imagine that the ORISPL IDs that are in the CEMS data are all going to show up as having the same timezones as their plant_id_eia counterparts.

Yeah, I think that's right. I can do a quick check to make sure. But in the scheme of things, I think whether we merge in the crosswalk `plant_id_eia` values has to do with a few factors: 

1) Whether it makes sense given how much processing power it takes to do anything to CEMS
2) Whether we want to consider `plant_id_eia` and `plant_id_epa` independent ids or whether `plant_id_epa` is a less correct version of `plant_id_eia` that needs to be fixed.

**Comment by grgmiller** [comment]
My understanding is that many years ago, the EPA just copied the EIA plant IDs into their databases, but over time as there were occasional changes to the EIA plant IDs, the EPA never synced their plant IDs with EIA, so the EPA plant IDs essentially fell out of date. So if you're using the crosswalk for data that is older (say 2000s), the EPA plant ID might actually be correct because it was before the EIA ID changed.

I would suggest confirming this by checking the data dictionary, but I would suspect that the `CAMD_STATUS_DATE` indicates when the EIA plant ID changed.

**Comment by aesharpe** [comment]
I've gone ahead and integrated these changes into this PR: #1692
