### ISSUE TITLE
Harmonize CEMS and EIA plant (ORISPL) codes?

### ISSUE THREAD

**Issue by karldw** [catalyst-cooperative/pudl#178]
Not every EIA plant is in CEMS, but I think (almost) every CEMS plant should be in the EIA tables. `plants_entity_eia` has the list of plant codes the PUDL database knows about.

There are known discrepancies, listed [here](https://www.epa.gov/sites/production/files/2018-02/documents/egrid2016_technicalsupportdocument_0.pdf#page=104) and in the [older eGRID](https://www.epa.gov/sites/production/files/2018-02/egrid2016_all_files_since_1996.zip) files.

**Edit (2020-11-17):** The link to the current eGRID changed. The most recent eGRID technical support document is here: https://www.epa.gov/sites/production/files/2020-01/documents/egrid2018_technical_support_document.pdf#page=124 ("Table C-5. Crosswalk of EIA ORISPL ID changes to EPA/CAMD ORISPL IDs")

**Edit (July 2022):** This is related to the EPA-EIA crosswalk that is getting integration into PUDL.

**Comment by michaelpburt** [comment]
This EPA API may be beneficial. It provides programatic crosswalking between EPA ID's and EIA plant codes. It is worth exploring as you work to harmonize these two sources.

https://github.com/USEPA/FRS-getfacilities-samples/blob/master/EIA-EPA_Mashup.md

**Comment by zaneselvans** [comment]
Wow that looks awesome. I've been wondering what other sources the `unit_id_epa` and `facility_id` fields in CEMS hourly map to.

**Comment by karldw** [comment]
It's also worth taking a look at NEEDS, which has several columns for different unit IDs.
https://www.epa.gov/airmarkets/national-electric-energy-data-system-needs-v6

**Comment by karldw** [comment]
Here's a snippet to pull plant EIA 860 info from that FRS site:

```python
from json import JSONDecodeError
from functools import lru_cache
import requests
import pandas as pd

# Cache this so we don't have to keep loading the same page
@lru_cache(512)
def download(url):
    return requests.get(url)

def one_plant_info(plant_id_eia):
    url_template = "https://ofmpub.epa.gov/enviro/frs_rest_services.get_facilities?pgm_sys_acrnm=EIA-860&output=JSON&pgm_sys_id={}"
    url = url_template.format(plant_id_eia)
    request = download(url)
    if request.status_code > 399:
        print("Failed to retrieve data for ", plant_id_eia)
        return None
    try:
        json_data = request.json()["Results"]["FRSFacility"]
    except (JSONDecodeError, KeyError):
        print("Failed to parse json info for ", plant_id_eia)
        return None
    return pd.io.json.json_normalize(json_data)

one_plant_info(58898)
```
Relevant for @cmgosnell's entity compilation too!
Could be used in #166 if you want to pull from a different data source for the tests.

More detail here, particularly Appendix A:
https://www.epa.gov/frs/frs-rest-services

**Comment by karldw** [comment]
For completeness I'm linking @gschivley's [comment](https://github.com/catalyst-cooperative/pudl/issues/535#issuecomment-584656153) here. Note that there are cases where the EPA and EIA plant codes match for some but not all of the units within a plant (e.g. El Segundo in California).

**Comment by grgmiller** [comment]
I wanted to link to this comment here about the EPA-EIA crosswalk document as it seems helpful for this task
https://github.com/catalyst-cooperative/pudl/issues/535#issuecomment-586530853

I am currently working on filling the missing associations between the EPA plant_id and the EIA plant_ids and will post the updated associations (and code I used to match them) once I have that.

**Comment by grgmiller** [comment]
I now have a nearly complete matching of EPA "ORISPL_CODE" (plant_id) to EIA plant_id, based on the crosswalk document provided by the EPA. I wanted to get started contributing to the development of `pudl.transform.epacems.harmonize_eia_epa_orispl`, but I had a couple of questions about how best to implement this harmonization. 

Particularly, I was wondering where the mapping values should live... should it be a dictionary in `constants.py`? Should it be part of the glue module?

There are only 42 plants for which the eia plant_id differs from the epa plant_id.

There are 6 EPA plants that seem not to exist in the EIA data (which seem to all be cogen plants).

**Comment by zaneselvans** [comment]
Hey @grgmiller, So, what's the nature of the difference in the IDs? It's such a small number -- is this a kind of historical error? Would it make sense to simply replace the `ORISPL_CODE` field in CEMS with the EIA IDs? Or are there other data where the EPA IDs will be required for integration?

If we need to preserve both sets of IDs, then I imagine we should make this into a glue table that connects EIA and EPA CEMS. @cmgosnell do you have feels about this?  What list of EIA IDs are you comparing against right now? The entity tables? IIRC there's also a small number of IDs that @karldw compiled that exist in CEMS but not in EIA 860/923, so maybe the 6 you've come across are in there? Or could be added to that list?

**Comment by grgmiller** [comment]
I think since PUDL already replaces the `ORISPL_CODE` field name with `plant_id_eia` at some point in the ETL process, we could simply replace the epa code with the correct eia code. I am not aware of any other places where the EPA ID would be required for integration. However, it looks like replacing the EPA codes with the correct EIA id will need to be a little more nuanced, as there are two types of differences:

1. The EPA ID and EIA ID are simply different. One example is the "El Segundo" plant which is ID "330" in CEMS and ID "57901" in EIA. This could be a simple replacement

2. The EIA data has assigned different generators at the same plant to two different plant_ids, and thus the CEMS data matches to two IDs in EIA. For example, the "Middletown" plant (EPA ID 562) matches to EIA IDs 562 and 57068. In the EIA data, generators 2, 3, 4, and 10 are assigned to plant ID 562, but generators 12, 13, 14, and 15 are assigned to plant_id 57068.

In this second case, we could still make the replacement, but it will require two sets of keys: EPA plant_id to EIA plant_id, and EPA unit_id to EIA generator_id. Luckily, the EPA crosswalk spreadsheet contains both plant associations and unit associations. This means we may have to use both plant and unit associations to get the proper `plant_id_eia` and then while we are at it, it might be worth addressing https://github.com/catalyst-cooperative/pudl/issues/535 at the same time. 

I was using the list of EIA IDS from `plants_entity_eia.csv`. However, it looks like this table also includes plant ids from sources besides EIA-860, because halfway down the table, most the column entries are missing, and I can't seem to find those plant_ids in the EIA datasets (unless they are in the really old EIA-860 datasets? I didn't look there). Do you know where all of the entries in plants_entity_eia are being pulled in from?

**Comment by zaneselvans** [comment]
The entity IDs are "harvested" from all of the integrated EIA data -- @cmgosnell wrote this code, which lives in the `pudl.transform.eia` module. Because we use the entity tables as the home tables for those IDs, and they are primary keys, or portions of composite primary keys, we need to make sure that we have *all* values accounted for.  So late in the Transform step, the harvesting process exhaustively searches for all IDs in the EIA data -- this hasn't (yet) been extended to the CEMS data because it's too large for it to be convenient, and so we've been wondering if we should do it some other way.  And then there's the small collection of EIA IDs that appear in CEMS but not in EIA probably because there's like 15 more years of CEMS data, but @karldw would know more about that.

**Comment by grgmiller** [comment]
In that case, perhaps some of the differences in the EIA and EPA codes are historical artifacts... eg the EIA updated some plant codes but didn't tell the EPA, and the historical plant codes lived on in the EPA database. It might be useful in the `plant_entity_eia` table to add a column listing the source of the plant key (e.g. 2018 EIA-860 or 2001 EIA-923). This could be helpful if perhaps there is a different plant_id association based on what year the data is coming from?

For reference @karldw the EPA plant_ids that I was unable to locate in IEA are: 

plant_name | plant_id_epa
-- | --
Blackstone | 1594
AbiBow US Inc. - Catawba Operations | 2440
The Ohio State University | 50044
Veolia Energy Philadelphia - Schuylkill | 50607
North East Cogeneration Plant | 54571
Valero Refining Company-Tennessee, LLC | 55703

However, it appears that all of these plants do actually exist in the `plants_entity_eia` table near the bottom, so it would be useful to know where these entries were ingested from... perhaps they are just really old retired plants at this point.

**Comment by grgmiller** [comment]
The cleaned crosswalk table can be found here: https://github.com/grgmiller/EPA-EIA-Unit-Crosswalk

**Comment by karldw** [comment]
For more detail on the mismatch for plants that appear in both datasets, it might be worth taking a look at the eGRID link at the beginning of this thread.

@zaneselvans, most of the plants that appear in CEMS but not the EIA are generators that closed before the PUDL EIA data starts. There are also a few cogen plants, as @grgmiller pointed out, and some plants that are required to monitor emissions but aren't electricity generators, like refineries.
