### ISSUE TITLE
Change lifecycle rule of pudl-etl-logs bucket

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#1888]
Currently, all outputs of nightly builds are stored in standard storage in the `pudl-etl-logs`. The bucket is up to about 400 GB. Each successful deployment saves 12 GB to the bucket. 400 GB in standard storage costs us $8 a month. This will start to cost more the more successful runs we have. 

I propose we add a [lifecycle rule](https://cloud.google.com/storage/docs/lifecycle) to the bucket to archive or delete objects that are more than a month old. This would ensure our storage costs don't increase for out-of-date data.

@zaneselvans What do you think? Any opinions on how long the outputs should be retained and if they should be archived or deleted?

**Comment by zaneselvans** [comment]
I agree that we don't need to keep more than a month of past builds. If we haven't caught a problem and investigated it by then, it's probably too late.

When you say "deployment" do you just mean the nightly build? Or do you mean actually deploying the outputs to a place where they're usable (meaning the build and validation succeeded, and we updated the outputs associated with the `dev` branch in the intake catalog, redeployed datasette, etc.)?

All of the places where we'll copy the outputs when the builds succeed will be in other buckets not subject to the lifecycle rule right?

Right now the build runs every night no matter what, right? Even if there are no changes to the `dev` branch (because it's not easy to tell it to skip the build if nothing has changed?) If so then we'd always have *some* output.  If it was only building when the code changes, and we didn't merge anything into `dev` for a month (which seems unlikely) then there wouldn't be any build outputs in the `pudl-etl-logs` bucket.  But that doesn't matter because it's only a staging area? Nothing actually attempts to access those outputs there, other than to copy (deploy) them to where they become persistent publicly visible resources, right?

Side-note: `pudl-etl-logs` seems like a misleading name for that bucket if it contains not only the logs but also the build outputs.

**Comment by zaneselvans** [comment]
On archive vs. delete I think we can delete. In theory if we needed to could we recreate the build given the commit?  I guess not really since we don't pin our dependencies with something like `pip-tools`. We should get that set up.

But still the nightly build outputs are ephemeral, unless the build succeeds and the outputs get deployed to public locations. And even then they're ephemeral unless it's a tagged commit, which I hope we can keep indefinitely, maybe with archiving after a year or something.

**Comment by bendnorman** [comment]
A month retention period sounds good to me. 

When I say "deployment" I mean nightly build. I was using deployment to distinguish it from the docker image build step. I'm happy to just call nightly builds. However, there are some GCP resources that use the word "deployment".

I can also rename the `pudl-etl-logs` to `pudl-etl-nightly-build-outputs` or just `nightly-build-outputs`.
