### ISSUE TITLE
Missing variables in `plants_eia860` table from `pudl-v0.6.0-2022-03-12` release

### ISSUE THREAD

**Issue by jacobalder** [catalyst-cooperative/pudl#1944]
### `iso_rto_code` and other variables missing from `plants_eia860` table in `pudl-v0.6.0-2022-03-12` release
Below, the list of variables in the `plants_eia860` table from the most recent `pudl-v0.6.0-2022-03-12` release. This is not the beta version on [Zenodo Archives](https://sandbox.zenodo.org/record/764696), but it does appear to be at least a [recent release](https://github.com/catalyst-cooperative/pudl/issues/1497). I downloaded this instance in April 2022. The problem? It does not match the list of variables in the [SQLite plants_eia860 table](https://data.catalyst.coop/pudl/plants_eia860)?

 | **SQLite table** | **pudl-v0.6.0-2022-03-12 release** |
 |-------------------|-----------|
 | plant_id_eia | TRUE  |
 | report_date | TRUE |
 | ash_impoundment | TRUE |
 | ash_impoundment_lined | TRUE |
 | ash_impoundment_status | TRUE |
 | balancing_authority_code_eia | FALSE |
 | balancing_authority_name_eia | FALSE |
 | datum | TRUE |
 | energy_storage | TRUE |
 | ferc_cogen_docket_no | TRUE |
 | ferc_exempt_wholesale_generator_docket_no | TRUE |
 | ferc_exempt_wholesale_generator | FALSE |
 | ferc_small_power_producer_docket_no | TRUE |
 | ferc_small_power_producer | FALSE |
 | ferc_qualifying_facility_docket_no | FALSE |
 | grid_voltage_1_kv | FALSE |
 | grid_voltage_2_kv | FALSE |
 | grid_voltage_3_kv | FALSE |
 | **iso_rto_code** | **FALSE** |
 | liquefied_natural_gas_storage | TRUE |
 | natural_gas_local_distribution_company | TRUE |
 | natural_gas_storage | TRUE |
 | natural_gas_pipeline_name_1 | TRUE |
 | natural_gas_pipeline_name_2 | TRUE |
 | natural_gas_pipeline_name_3 | TRUE |
 | nerc_region | TRUE |
 | net_metering | TRUE |
 | pipeline_notes | TRUE |
 | primary_purpose_id_naics | FALSE |
 | regulatory_status_code | TRUE |
 | reporting_frequency_code | TRUE |
 | FALSE | respondent_frequency |
 | sector_id_eia | FALSE |
 | sector_name_eia | FALSE |
 | service_area | TRUE |
 | transmission_distribution_owner_id | TRUE |
 | transmission_distribution_owner_name | TRUE |
 | transmission_distribution_owner_state | TRUE |
 | utility_id_eia | TRUE |
 | water_source |TRUE |
 | data_maturity | FALSE |

### Severity
How badly is this bug affecting you?
 - **Medium-Low:** This component is not crucial to my analysis, but without it makes the analysis more complicated. Specifically, the variable I need the most is the `iso_rto_code` and it's unfortunately not there. I can do a workaround by pulling that from the SQLite table, but it's not very elegant.

### To Reproduce
I'm using Docker and JupyterHub, so the code in python is
`A = """
SELECT *
FROM
  plants_eia860 AS plants;
"""
a = pd.read_sql(A,pudl_engine)
a`

 - The bug appears to be related to the software / database? I've attached the `settings.yml` file I'm using to specify which data to load, and make a note of where in the ETL process the error is happening. See here: 
[settings.zip](https://github.com/catalyst-cooperative/pudl/files/9608080/settings.zip)
 - Have I found an error or inconsistency in the data that PUDL brings together? Seems to be a difference in the tables on SQLite and in the database downloaded from Zenodo.
 - Does the problem happen when I'm starting up the database (importing data) or does it happen later when I'm trying to use the database? When I'm trying to use the database.

### Expected behavior
I'd like to use `iso_rto_code` from the `plants_eia860` table. This variable is not available in the distribution I downloaded from Zenodo archives.

### Software Environment?
 - Operating System: MacOS 10.15
 - Python version and distribution: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
[GCC 9.4.0]
 - How did you install PUDL?
    - I downloaded from Zenodo archives and then ran `docker-compose up`. This is the first table I've run into issues with -- it does not appear to be a problem with other tables, e.g., `generators_eia860` or `utilities_eia860`.

**Comment by zaneselvans** [comment]
Hi there! Glad you've found PUDL useful, and sorry this discrepancy is causing you difficulty.

Since the release in March we've moved some of the attributes around. It turned out that some of the columns we'd previously inferred to be static and unchanging (like `iso_rto_code`) actually do change very occasionally, and so they were moved from `plants_entity_eia` (which has no `report_date`) to `plants_eia860` (which has annual resolution).

We also added in columns like `respondent_frequency` which had previously been excluded incorrectly, and added the `data_maturity` column when we integrated the early release data from EIA for 2021.

The data published on https://data.catalyst.coop is built using the `dev` branch of the repository, which gets updated every few days (whenever the nightly builds succeed after integration of new data or code). There's metadata describing it published alongside (all the column descriptions there), and also [the PUDL data dictionary on Read The Docs](https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/pudl_db.html).

Nightly build outputs are also deposited in the public (requester-pays) storage bucket: gs://intake.catalyst.coop/dev if you want to download them directly.  You can also download the whole database behind the Datasette deployment. There's a small link at the bottom of the PUDL DB page: https://data.catalyst.coop/pudl

**Comment by jacobalder** [comment]
Great! Thank you for clarifying--and for your hard work on PUDL! I've pulled the updated DB and have it working now.
