### ISSUE TITLE
epacems parquet files seem to be missing data

### ISSUE THREAD

**Issue by grgmiller** [catalyst-cooperative/pudl#1949]
As I was exploring https://github.com/catalyst-cooperative/pudl/issues/1864, I happened to notice that there might be some instances where the epacems parquet files are missing data that appears in the raw cems data. I don't know how widespread this may be, or whether it has already been fixed somewhere on the dev branch since the latest pudl data release on zenodo (v4.0.0 released 3/12/22). 

Specifically, I noticed that for unitid `WAP8` at plant `3470`, there is hourly data reported in the `2020tx05.csv` file downloaded from https://gaftp.epa.gov/DMDnLoad/emissions/hourly/monthly/2020/2020tx05.zip, but when I load data from the parquet file (downloaded from https://zenodo.org/record/6349861/files/pudl-v0.6.0-2022-03-12.tgz), there is no data for this unit in May. 

I notice that the parquet file does contain data for unit `WAP8` until the end of March, and it also contains data for all other units at this plant (WAP1 - WAP7) after March - just this single unit seems to be missing in some months. 

It seems strange that the PUDL ETL would be selectively dropping data like this, so other possible explanations I can think of include:
- The raw CEMS data was also missing data for WAP8 after March 2020 at the time when v4.0.0 data was released, and it has since been added
- pudl is pulling data from a different source than the one I am using (although it looks like based on the [documentation ](https://catalystcoop-pudl.readthedocs.io/en/dev/data_sources/epacems.html)that pudl is also downloading the bulk zip files from the same FTP site)
- This is a known issue that I was unable to find when searching the list of existing issues, which may or may not have already been fixed, but I haven't re-run the pudl ETL on my computer to check what the latest version of the ETL creates)

Here's an example of what the raw csv file shows for this unit:
![image](https://user-images.githubusercontent.com/45949268/192115004-6a56cbfc-213e-44fa-b377-f8cb34844996.png)

And here's what I get if I load the parquet file and explore the data:
WAP8 data in March:
![image](https://user-images.githubusercontent.com/45949268/192115098-f15fe474-1b2c-4990-bd67-02d1b3a60923.png)
No WAP8 data in May:
![image](https://user-images.githubusercontent.com/45949268/192115060-55d04182-7c4b-48a9-b793-1f34f08add11.png)
But there is data for other units in May:
![image](https://user-images.githubusercontent.com/45949268/192115035-15e19c49-c77a-4d73-857a-a9661d86ab15.png)

**Comment by aesharpe** [comment]
Hmm, I checked whether this was the case with the data on my local machine (from the most recent `dev` push), and I found data for May! Here's a snapshot of what I found. Note that the values are off by 6 due to timezone changes.

| operating_datetime_utc    |   plant_id_eia | emissions_unit_id_epa   |   gross_load_mw |   so2_mass_lbs |   nox_mass_lbs |   co2_mass_tons |
|:--------------------------|---------------:|:------------------------|----------------:|---------------:|---------------:|----------------:|
| 2020-05-01 00:00:00+00:00 |           3470 | WAP8                    |             496 |          446.3 |          185.2 |           485.6 |
| 2020-05-01 01:00:00+00:00 |           3470 | WAP8                    |             338 |          292   |          134.2 |           360.8 |
| 2020-05-01 02:00:00+00:00 |           3470 | WAP8                    |             254 |          211.5 |          118.8 |           283.2 |
| 2020-05-01 03:00:00+00:00 |           3470 | WAP8                    |             253 |          236.4 |          123.3 |           287.4 |
| 2020-05-01 04:00:00+00:00 |           3470 | WAP8                    |             253 |          262.5 |          125   |           291.4 |
| 2020-05-01 05:00:00+00:00 |           3470 | WAP8                    |             266 |          295   |          130.8 |           304.9 |
| 2020-05-01 06:00:00+00:00 |           3470 | WAP8                    |             253 |          271.3 |          125.4 |           292.3 |
| 2020-05-01 07:00:00+00:00 |           3470 | WAP8                    |             242 |          248.3 |          125.5 |           274.1 |
| 2020-05-01 08:00:00+00:00 |           3470 | WAP8                    |             197 |          201.2 |          122.5 |           233.5 |
| 2020-05-01 09:00:00+00:00 |           3470 | WAP8                    |             182 |          188.3 |          123.8 |           223.9 |

**Comment by aesharpe** [comment]
Closed because data seems to be there.
