### ISSUE TITLE
`entity_types_eia` table is broken on datasette

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#2248]
### Describe the bug
The `entity_types_eia` table is documented in the [data dictionary](https://catalystcoop-pudl.readthedocs.io/en/latest/data_dictionaries/pudl_db.html#entity-types-eia) but the datasette link is [broken](https://data.catalyst.coop/pudl/entity_types_eia). 

### Bug Severity
How badly is this bug affecting you?
 - **Medium:** With some effort, I can work around the bug.

### Expected behavior
I'm confused about what the `entity_type_eia` table is and where it comes from. It looks like it is hardcoded in the `pudl.metadata.codes` module but it isn't being loaded to the database thus not showing up in datasette. Is this table copied from the 861 output table? Is this just a workaround until 861 is properly added to the ETL? Should we remove this table from the data dictionary so there isn't confusion?

**Comment by zaneselvans** [comment]
Unfortunately this table doesn't yet exist, because we didn't finish reconciling the minor differences between the entity types used in EIA-860 and EIA-861, as described in #1392.

There's inconsistency in how these entity / ownership types are reported across different years, across different tables, and between the two datasets.

**Comment by bendnorman** [comment]
Closed by https://github.com/catalyst-cooperative/pudl/pull/3086
