### ISSUE TITLE
Integrate OGE subplant id cleaning methodology into PUDL

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/pudl#2456]
After scoping in #2400 we've decided to integrate the OGE cleaning methodology for pudl subplant ids directly rather than try and reinvent it / directly integrate the BGA table with the EPACAMD-EIA crosswalk. At least for now.

**Comment by arengel** [comment]
One minor point on integrating the OGE `subplant_id` refinements into PUDL. I've been working with the OGE crosswalk data and have noticed that in some cases `emissions_unit_id_epa` is missing for retired combustors, I believe this is a result of the performance optimization in singularity-energy/open-grid-emissions#239 (first bullet of 'Other updates').

I would propose two (hopefully) minor modifications to OGE's method:
1. Include all required fields required for connecting EIA and CAMD data for all existing and retired generators/units for which the underlying EPA crosswalk has connections. I think those fields would be `plant_id_eia`, `plant_id_epa`, `generator_id`, `emissions_unit_id_epa`, and `subplant_id`.
2. Make `subplant_id` s stable across years. That this is not the case is mentioned in the other bullets in the above referenced PR that describes  the `subplant_id`.

I think these two are related and so that addressing one should address the other as well.
