### ISSUE TITLE
Investigate subplant_id coverage/usability

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#2548]
```[tasklist]
- [x] are there any boilers that are not covered by the subplant_id?
  - [x] from the boilers\_entity\_eia table?
  - [x] from the boiler\_fuel\_eia923 table?
- [x] are there any subplant_ids that only partially encompass units reporting to the generation_fuel_eia923 table?
- [x] are there any subplant_ids that only partially encompass units reporting to the boiler_fuel_eia923 table?
```

**Comment by cmgosnell** [comment]
(i'm going to use this comment as my running notes... its currently a WIP. Will add things as they come up)

# Setup
```
# Import stuff and pull in tables we'll need
from dagster import AssetKey 
import pudl
from pudl.etl import defs

epacamd_eia_subplant = defs.load_asset_value(AssetKey("epacamd_eia_subplant_ids"))
epa_eia = defs.load_asset_value(AssetKey("epacamd_eia"))
gens_eia860 = defs.load_asset_value(AssetKey("generators_eia860"))
bga_eia860 = defs.load_asset_value(AssetKey("boiler_generator_assn_eia860"))
unit_ids_epacems =defs.load_asset_value(AssetKey("emissions_unit_ids_epacems"))
generators_entity_eia = defs.load_asset_value(AssetKey("generators_entity_eia"))
bf_eia923 = defs.load_asset_value(AssetKey("boiler_fuel_eia923"))
gf_eia923 = defs.load_asset_value(AssetKey("generation_fuel_eia923"))
boilers_eia = defs.load_asset_value(AssetKey("boilers_entity_eia"))
```


# Boiler Coverage in BGA
I first had to check whether there are boilers that don't show up in the boiler_generator assn

![Image](https://user-images.githubusercontent.com/25487998/234287444-bc427f23-dc06-4940-992f-cfb010bcfb8a.png)

**Comment by arengel** [comment]
I've been testing out the new `epacamd_eia_subplant_ids` table in our fossil plant cost analysis module and have found 3 issues:
1. plant_id_eia=4042, in this plant there is a camd_unit that maps to two different generators, one of which is missing a unit_id_pudl, this leads to that part of the camd_unit getting a different subplant_id. From what I am seeing for this plant, it seems like the whole plant should be one subplant.
2. plant_id_eia=2708, in this plant there are two camd_units (2A and 2B) that are each associated with two generators (one in common), the non-common ones do not have unit_id_pudls so these camd_units are associated with different subplants.
3. plant_id_eia=55126, here there are two camd_units that are split between subplants, I think again because some of the generators do not have unit_id_pudls.

My process for finding these issues is as follows:

```python
df = epacamd_eia_subplant_ids.groupby(
     ["plant_id_eia", "emissions_unit_id_epa"]
).agg({"subplant_id": pd.Series.nunique})
assert df[df.subplant_id > 1].empty
```

I also test the following but this version does not find issues:

```python
df = epacamd_eia_subplant_ids.groupby(
     ["plant_id_eia", "generator_id"]
).agg({"subplant_id": pd.Series.nunique})
assert df[df.subplant_id > 1].empty
```

**Comment by cmgosnell** [comment]
I pulled out these weird groupings into its own specific [issue](https://github.com/catalyst-cooperative/pudl/issues/2583) and am closing this one out for now.
