### ISSUE TITLE
enable labeling for straightforward rate base calcuations from the exploded FERCtables

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#2600]
```[tasklist]
- [x] attempt a translation of jon's current dbf-level metadata
- [x] create tagging CSV with `xbrl_factoid_name` and other dimensions for `in_rate_base` (`all`, `partial`, `none`)
- [x] enable dimension specific tagging (design like calc fixes - only require saving dimension specific in CSV & infer the rest based on `table_dimensions_ferc1`
- [x] ensure tags can be added with new dimensions into the forest
- [x] prep reviewable tags w/ example data for rmi folks to vet (see https://github.com/catalyst-cooperative/pudl/pull/2832)
- [x] integrate and updates from rmi team
- [ ] https://github.com/catalyst-cooperative/pudl/issues/2892
```

### From tbl transforms
* [x] `utility_function` -> `utility_type` enum
* [x] `FERC_class` -> `plant_function` enum
* [x] `FERC_class_detail` -> `xbrl_factoid`

### Determinable from :boom: metadata
* [ ] `electric/non-electric/mixed` (**mostly** determinable hopefully!)
* [ ] `is there a detail table in FERC that differentiates electric/not?` (I think think this should be determinable but lmk if i'm missing something here)

### Stored metadata
* [x] `is this actually in rate base?` - > `in_rate_base` enum all/partial/none @ the `xbrl_factoid` level
* [x] `rate_base_component` ->  something. It looooooks like this one we could build a map for this with unique ~90 groupings of `utility_function` & `FERC_class` instead of mapping every single ferc line type. so 🤞  this can be @ the `plant_function`/`utility_type` level.
* [ ] `rate_base_sub_component` ?

**Comment by jrea-rmi** [comment]
@cmgosnell are you saying electric/non-electric/mixed should be determined from FERC metadata? I think that's generally true, like the summary of utility plant table has that information in it and some of the detail tables are specifically the electric component. Some lines of the balance sheet and income statement are obviously from electric or non-electric operations, but I don't think the FERC metadata has that information in it.

in_rate_base should probably be a string with options of all/partial/none (from your first task) rather than a boolean (from your stored metadata checklist). 

rate_base_component is the categorization we show on the finances dashboard of the Utility Transition Hub. It's the same as FERC_class for electric plant in service categories, an "other" category for mostly non-physical assets in rate base. I think the categories we used here are negotiable: we could probably use FERC_class + in_rate_base and fill missing FERC_class with "other" as the rate_base_component.

FERC_class_detail was directly from FERC tables, compiled from the most detailed level of explosion that we had. So it's the row description from the electric plant in service table, accumulated provision for depreciation... table, balance sheet, whatever the most detailed breakout of a line was.

rate_base_sub_component provides some detail of rate_base_component that we thought was generally useful for investigating cases where the "other" category of rate base was significant. We included it in the data download file we have on the Hub website. But I could see that changing to a version where we include some version of the FERC_class and FERC_class_detail in that table instead for someone (including ourselves) doing deep investigation of what the components of rate base are for a utility or set of utilities.

**Comment by cmgosnell** [comment]
ty @jrea-rmi  this is is all really helpful!!

Yes, I get the sense that if we have all of the tables that do have clear `utility_type` labels and easy to use relationships between fields/tables/relationships with those same `utility_type` labels we should be able to do a pretty good job. But you've almost certainly right that when there are instances of specific types that are probably clear to you but are within tables that have for instance `total`s that we've filled in across the board. We'll have to look out for those and add in a step that adds some of this non-xbrl-metadata info.

and good point on the `partial` option for `in_rate_base`!

On `rate_base_component` and `rate_base_sub_component` these seem pretty straightforwardly additional hand-compiled metadata that should be able to be mapped directly onto the exploded tables.

**Comment by cmgosnell** [comment]
lol jk more tags exist besides just in_rate_base

**Comment by zaneselvans** [comment]
Trying to use this CSV to tag the calculation tree, I found that there were many duplicate records when using `(table_name, xbrl_factoid)` as the index and trying to read `in_rate_base` as the value column.  In the case of `(utility_plant_summary, accumulated_provision_for_depreciation_amortization_and_depletion_of_plant_utility)` it was tagged with both `yes` and `no`.

```py
pkg_source = (
    importlib.resources.files("pudl.package_data.ferc1")
    .joinpath("xbrl_factoid_rate_base_tags.csv")
)
with importlib.resources.as_file(pkg_source) as tags_csv:
    in_rate_base = pd.read_csv(tags_csv)

idx_cols = ["table_name", "xbrl_factoid"]
in_rate_base[in_rate_base.duplicated(subset=idx_cols, keep=False)].sort_values(idx_cols)
```

**Comment by jrea-rmi** [comment]
I will have to get a double check from Ryan & David, but I believe I expect all `(utility_plant_summary, accumulated_provision_for_depreciation_amortization_and_depletion_of_plant_utility)` where `utility_function == electric` to be tagged `in_rate_base = all`

**Comment by cmgosnell** [comment]
i'm marking this as closed now that we integrated all of rmi's tag updates
