### ISSUE TITLE
Check and debug inter-table and inter-dimensional calculations for both exploded tables

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl#2703]
In #2669 we added inter-table and inter-dimensional inter-table calculations into the process of the table explosion. We should look at these calculations and debug signs, component names etc. to improve calculation accuracy. 

```[tasklist]
- [x] Identify troublesome calcs
- [x] For each calculation: identify components, look for sign errors, look for missing components
- [ ] https://github.com/catalyst-cooperative/pudl/issues/3064
```

- Update `accumulated_depreciation` component to `in_service` plant status for `depreciation_utility_plant_in_service`
-  add `total` `plant_status` for `construction_work_in_progress` link between `balance_sheet_assets_ferc1` and `utility_plant_summary_ferc1`
-  add `total` `plant_status` for the `accumulated_provision_for_depreciation_amortization_and_depletion_of_plant_utility` link between `balance_sheet_assets_ferc1` and `utility_plant_summary_ferc1`

**Comment by cmgosnell** [comment]
# Balance sheet asset explosion inter-table calc debugging notes:

High level # of factoids in the inter-table reported factoids that are off from their calculated value from their sub-components:

```
xbrl_factoid
utility_plant_in_service_classified_and_property_under_capital_leases                 3741
utility_plant_net                                                                     2106
accumulated_provision_for_depreciation_amortization_and_depletion_of_plant_utility    2080
utility_plant_and_construction_work_in_progress                                       2073
construction_work_in_progress                                                         1906
depreciation_utility_plant_in_service                                                  488
utility_plant_in_service_plant_purchased_or_sold                                        35
Name: count, dtype: Int64
```

## `utility_plant_in_service_classified_and_property_under_capital_leases`
In trying my little debugging test on the calcs that checks whether the absolute difference between the reported and calculated values are the exact same value of other components I learned that the vast majority (3167/3741) of the errors in `utility_plant_in_service_classified_and_property_under_capital_leases` are because of the error that Jon id-ed when we were first starting this journey: many utilities include `utility_plant_in_service_completed_construction_not_classified` in `utility_plant_in_service_classified_and_property_under_capital_leases`. This happens across all years. It doesn't totally make sense because the sub-component oft included is specifically "not-classified". I. tried adding this into the mannual calc fixes and it caused a 67% error rate instead of the existing 59%.

**this accounts for 24% of the errors in the balance sheet asset explosion.**

**Comment by zaneselvans** [comment]
You probably already saw this but it looks like there might be a small population of records with a sign error -- the ones that head down and to the right from the origin.

**Comment by cmgosnell** [comment]
> You probably already saw this but it looks like there might be a small population of records with a sign error -- the ones that head down and to the right from the origin.

yes i already fixed some of them and described the problem in the section above `depreciation_utility_plant_in_service`

**Comment by cmgosnell** [comment]
After some work via #3064 and #3078... i got the balance sheet asset inter-table calcs cleaned up a bit but they are still not awesome and none of these fall into the "off-by fact x" pattern. Here is the summary outputs:

![image](https://github.com/catalyst-cooperative/pudl/assets/25487998/bbd0339a-fd75-446e-b315-0f93df5ae9c7)


![image](https://github.com/catalyst-cooperative/pudl/assets/25487998/b9e15b2e-4c89-460d-a563-3ddd636560e3)

**Comment by zaneselvans** [comment]
Ugh I love your plotting theme.

**Comment by cmgosnell** [comment]
I'm going to call this good enough for now. If we get further direction for further cleaning we can certainly open a new more directed version of this issue.
