### ISSUE TITLE
Make nightly build outputs easier to download and access remotely

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3079]
Our main data product `pudl.sqlite` is about 12 GB which is a pain in the butt to download and work with on standard github runners which only have 14 GB of disk space. We discussed options in #3071 and decided to compress our `.sqlite` files and write all of `pudl.sqlite`'s tables as parquet files so it's easier for users to pull compressed versions of individual tables.

## Outstanding questions
- What do we want the directory structure of a data release to look like?
- How do we want to create the parquet files? I see two options: 1) Have a post-processing script that reads all of the tables out of `pudl.sqlite`, correct the datatypes, and write them to parquet files or 2) add another type handler method in the `PudlSQLiteIOManager` that writes dataframes to parquet and sqlite (the class should probably be renamed too). I think option 2 is a little more straightforward, and we won't have to correct datatypes multiple times.
- Do we want to finish this before merging #2818?

```[tasklist]
- [x] #3084
- [x] Remove multi-file Parquet outputs prior to distribution
- [x] Remove unused local deployment scripts.
- [x] Rename FERC DBF derived outputs using `_dbf` mirroring `_xbrl` filenames. See #3094
- [x] Remove stale renamed outputs from `{gs,s3}://pudl.catalyst.coop/dev`
- [x] Update filenames referenced in the [PUDL Project Kaggle Dataset](https://www.kaggle.com/datasets/catalystcooperative/pudl-project)
```

**Comment by zaneselvans** [comment]
If we just convert `pudl.sqlite` to Parquet, I think we will run into undesirable datatype and row group behaviors.  Like every boolean column will turn into an integer column containing zeros and ones, and all the DateTime columns may end up getting stored as strings since that's how SQLite stores them, and we may end up with arbitrary row-groups that don't make any sense and don't enable ergonomic remote access to the files.

We already have a `ParquetIOManager` for managing Parquet outputs, and a `to_pyarrow()` method for generating PyArrow schemas. If we use that infrastructure to output the Parquet files as we go through the ETL we'll get much finer grained control and actually be able to take advantage of the features Parquet provides, and we also won't have to read all the data out of SQLite and just to write it into Parquet at the end of the process -- we can write it directly from the dataframes while they are already in memory (which is extremely fast).

**Comment by bendnorman** [comment]
I agree writing the parquet files during the ETL using an IO Manager is the way to go. We are only using `PandasParquetIOManager` to load data. The writing happens directly in the epacems assets. Also, I don't think dagster supports having two IO managers for a single asset though are some reasonable [work arounds](https://github.com/dagster-io/dagster/issues/9640).

I think it makes the most sense to create a new IO manager that writes the data to sqlite and parquet but loads the data from parquet because it should be faster and we don't have to do datatype conversions. Something like this

```python
class PudlIOManager(IOManager):

     def handle_output(context, df):
            context.resources.pudl_sqlite_io_manager.handle_output(context, obj)
            context.resources.pudl_parquet_io_manager.handle_output(context, obj)

     def load_input(context) -> pd.DataFrame:
            return context.resources.pudl_parquet_io_manager.load_input(context, obj)
```

`PandasParquetIOManager.load_input()` currently returns a dask dataframe which is nice for CEMS but isn't ideal for all of our other data. We could have a `PandasParquetIOManager` and a `DaskParquetIOManager`.

**Comment by zaneselvans** [comment]
Ahh right I forgot about the weirdness with writing all the Parquet files outs. It'll be the `PudlDoubleBarrelledIOManager`

I think we amy still end up needing to do datatype conversions since the PyArrow dtypes that the Parquet files use won't match up perfectly with the Pandas dtypes that the dataframes use (unless we switch to using PyArrow backed dataframes which seems like it would break literally everything everywhere all at once).  But this shouldn't be too annoying, since we already do it for the SQLite loading and hopefully the same method willl... just work? 😬 

But still this will still probably be much faster than reading out of SQLite.

Given that we'll now have *all* of the data available in Parquet, should we bundle together the EPA CEMS parquet outputs as "just another table" alongside all of the other Parquet files?  Seems like that will make more intuitive sense than having it isolated on its own at the top level.

**Comment by jdangerx** [comment]
Split Parquet stuff out into #3102 .
