### ISSUE TITLE
Double Free error

### ISSUE THREAD

**Issue by bendnorman** [catalyst-cooperative/pudl#3133]
We're experiencing a frustrating `double free or corruption (out)` error that initially did not provide any helpful stack traces. I enabled the python [`faulthandler`](https://docs.python.org/3/library/faulthandler.html) and got a more useful stacktrace: 
[Full double free stack trace.log](https://github.com/catalyst-cooperative/pudl/files/13603321/Full.double.free.stack.trace.log)

The last successful build was from commit `7cc80dab59437b0dda3dbac3bed28be5f4e33858` and this error popped up from commit `58bb0880b1ef6de8d3e1341b8c3f481e5a44d9f9`.

Here is what I know so far:
- The stack trace from `faulthandler` suggests the the double free is occurring while trying to connect to the postgres database.
- The ETL does not fail in CI or locally. CI and local deployment do not run in a docker container and use sqlite for dagster storage.
- The ETL does not fail when I run the ETL locally while using the Cloud SQL postgres as the dagster backend.
- This error does not occur when using sqlite as the dagster storage backend in the docker container and VM.
- This error does not occur while running the code from `58bb088` with the conda lock files from `7cc80da`. Here is the diff between the two [diff_env.txt](https://github.com/catalyst-cooperative/pudl/files/13603376/diff_env.txt). A few packages `psycopg2` depends on changed between the two commits (I think the versions from this command are out of date because I've been mucking with the version numbers):
```
✦ ❯ mamba repoquery depends psycopg2
Using local repodata...

Loaded current active prefix: "/Users/bendnorman/mambaforge/envs/pudl-dev"

 Name       Version Build                Channel     Subdir
────────────────────────────────────────────────────────────
 libpq      16.1    h6dd4ff7_0           conda-forge osx-64
 openssl    3.1.4   hd75f5a5_0           conda-forge osx-64
 psycopg2   2.9.7   py311h187f0af_1      conda-forge osx-64
 python     3.11.6  h30d4d87_0_cpython   conda-forge osx-64
 python_abi 3.11    4_cp311              conda-forge osx-64
```

Here are the version changes for the dependencies that changed:
```
-  - libpq=16.1=hfc447b1_0
+  - libpq=16.1=hfc447b1_2
-  - openssl=3.1.4=hd590300_0
+  - openssl=3.2.0=hd590300_1
```

Seems one of these indirect `psycopg2` dependencies is the culprit though I'm not sure how to proceed:
- Revert to `openssl=3.1.4`
- I'm not sure how to revert libpq
- Update `psycopg2=v2.9.9`
- We got a double free error a couple of weeks ago because of some conflict in `curl` installations. We resolved this by installing curl in the mamba env instead of using `apt-get` #3090. I could try to move our other packages installed using `apt-get` into the mamba env. I don't think every `apt-get` package is available via mamba though.

**Comment by zaneselvans** [comment]
* I've noticed that in recent solves the `psycopg2` dependency is being rolled back, so I suspect other folks downstream have run into some related problem and are pinning.
* There also seem to be ongoing issues with `openssl=3.2.0` which has been getting upgraded and then rolled back to `3.1.4` repeatedly, presumably as someone in our dependencies discovers issues and pins.
* The big `conda-lock.yml` is a useful resource for understanding who has what dependencies -- it lists the dependencies associated with each of the dependencies in the file, so you can search around for packages and see where they're coming from.
* `libpq` is produced by the `postgresql` [recipe on conda-forge](https://github.com/conda-forge/postgresql-feedstock/blob/main/recipe/meta.yaml) and they have been going back-and-forth on `openssl` versions it looks like.

So it seems like all of this is maybe due to the actual postgres packages, and maybe indirectly through them the `openssl` package... Do the builds work if we pin to `postgresql<16`?  Or if we pin `openssl<3.2.0`?  Though pinning a significant security package seems like not a wonderful idea, and we would want to try and un-pin it periodically...

**Comment by bendnorman** [comment]
Well, the recent downgrades of dependencies related postgres resolve this issue. Given conda lock updates everything that has changed it's hard to pin down exactly which dependency caused this in the first place. Maybe I could edit the conda-lock.yml file directly to verify `openssl=3.2.0` was the culprit?

Should we still pin `openssl>=3.1.4,!=3.2.0` for now?

**Comment by zaneselvans** [comment]
You can't hand-edit `conda-lock.yml` because it includes a bunch of other information about each package like the hash. I think we should do that `openssl` pin.

**Comment by jdangerx** [comment]
Status: we're figuring out how we want to manage the lockfiles in the future when some dependency breaks and we need to pin that dependency to a lower version.

**Comment by bendnorman** [comment]
The dependency changes introduced in https://github.com/catalyst-cooperative/pudl/pull/3132 ended up resolving this issue. openssl was downgraded to `3.1.4`, `libpq` build changed from `hfc447b1_2` to `hfc447b1_0`, `postgres` changed from `h8972f4a_2` to `h8972f4a_0`. Seems like other folks ran into this error and `postgres` rolled back some dependency versions.
