### ISSUE TITLE
Use merge queue in PUDL repo

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3317]
1. We require PRs to be up-to-date before merging, so we aren't running CI on some stale combination of `main` and your branch.
2. However, that means a lot of manual updating and re-running of CI.
3. [Merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) lets you put your PR in line. Then GH will run CI on the first PR in line. If it passes, it merges in and then the next PR gets updated to the latest version of the base branch, before then getting CI run on it. If CI fails, the PR is removed from the queue and GH moves on to the next one.

Practically, this means clicking "Merge when ready" when you want to merge something into `main`, instead of "Squash and Merge" or "Enable auto-merge."

Caveats/details:
* if we want this, _**we can't require RTD build before merge**_. We'll still trigger the build on the PR, and we can manually refuse to click "merge when ready" unless RTD succeeds. But RTD's builder doesn't support merge queues, yet.
* we are moving the integration tests to the merge queue - which means that they will no longer run until *after* you press "merge when ready." If they fail, you'll have to go back, fix it, and then re-queue it. But that also means that you don't have to worry about accidentally kicking of $$$ integration tests in your PR.
* there's also the concept of "merge groups" - so if, for example, 2 PRs get enqueued within 5 minutes of each other, we can actually run CI on the two of them combined. If that fails, we split that back up and re-run individually. This can save CI time also! 
* instead of running the CI one run at a time, we can run the CI with high concurrency - which means that if we have A, B, and C waiting in line, GH can run CI on (A + `main`), (B + (A + `main`)), and (C + (B + (A + `main`))) all at once. And if they all pass, all three get merged in order. If we only have concurrency of 1, then these three checks would run in series.

```[tasklist]
## Scope
- [ ] team knows how to work with merge queues: what happens in the normal path? what happens when CI fails?
- [x] current PR checks trigger on `merge_group:` event
- [x] `ci-integration` check gets pushed to `merge_group` only
- [ ] merge queues turned on in repo settings
```

**Comment by bendnorman** [comment]
This all sounds great! If we did want to run the integration tests without merging the PR in, would we just manually trigger a run? While we should run the integration tests locally, it's sometimes nice to have them running on Git Hub so I can switch over to another branch I'm working on.

**Comment by jdangerx** [comment]
That's a good idea! I'll shove `workflow_dispatch:` in as a valid trigger too.

**Comment by zaneselvans** [comment]
Very excited to get this in.

* I think it's fine for RTD to not be part of the check. The docs build happens in CI on GH as well, and RTD fails independently only rarely.
* With the merge groups, does GH **automatically** break the group up and re-run individual PRs if the group CI fails? That would be pretty cool.
* The automatic concurrency is also pretty cool. I was imagining we'd be able to merge at most one PR every 1.5 hours (which would be fine, honestly, but also very slow). I guess the danger here is that if there's a bug in A, then you've kicked off 3 runs which are doomed to fail instead of just 1.  If we're good about running the integration tests locally this shouldn't be a problem, but I think that's a habit we'll need to cultivate.
