### ISSUE TITLE
BadZipFile error sometimes shows up in nightly builds

### ISSUE THREAD

**Issue by jdangerx** [catalyst-cooperative/pudl#3358]
### Describe the bug

Sometimes when reading ZIP files in CI we get a `BadZipFile` error. It usually resolves itself on retrying the run.

This happened in #3271, #3338, and #3356 - so now we've seen this 3 times.

I think we can try:

1. Logging out more information about this BadZipFile
2. Adding retry logic to automatically retry just the resource request, instead of manually retrying the whole ETL.

### Bug Severity
How badly is this bug affecting you?
 - **Medium:** With some effort, I can work around the bug. Re-running the nightly build is annoying and slow, though.

### To Reproduce

Seems sporadic, but see the above issues for when it's happened before.

### Software Environment?

Our Docker container on GCP Batch

**Comment by jdangerx** [comment]
From inframundo discussion:

Both 714 and PHMSA have many excel files in the same ZIP file. Which might lead to many different processes opening up the ZIP file at the same time - which *should* be fine, but maybe is causing this error?

**Comment by bendnorman** [comment]
Opened a [PR](https://github.com/catalyst-cooperative/pudl/pull/3369) that adds context managers to our zipfiles.

In sprint check in we ruled out that the file was corrupted during the download because we validate the checksum. I think this is only true when we download directly from Zenodo. The nightly builds rely on the GCS cache which does not call `DatapackageDescriptor.validate_checksum()`. I can't tell from the Google API docs if this code [validates checksums](https://cloud.google.com/python/docs/reference/storage/1.37.1/blobs#downloadasbytesclientnone-startnone-endnone-rawdownloadfalse-ifgenerationmatchnone-ifgenerationnotmatchnone-ifmetagenerationmatchnone-ifmetagenerationnotmatchnone-timeout60-checksummd5):

https://github.com/catalyst-cooperative/pudl/blob/776b3e7a022c1c041e56c8cdfeae00ffcd5d28cd/src/pudl/workspace/resource_cache.py#L149-L152

**Comment by bendnorman** [comment]
Actually, I guess we know from #3364 that GCS is validating checksums.
