### ISSUE TITLE
include `balancing_authority_code_eia` in the `core_eia860m__changelog_generators` table

### ISSUE THREAD

**Issue by arengel** [catalyst-cooperative/pudl#3437]
**Is your feature request related to a problem? Please describe.**
I've been exploring the `core_eia860m__changelog_generators` table since we'd like to use it as our source for 860m data but our current uses of 860m data require BA codes. I like the changelog approach here (I'll admit to originally be skeptical), but I'd like to see it include all the fields in the source, which would mean adding back BA codes and sectors.

**Describe the solution you'd like**
Include balancing authority codes (and sectors) as reported in `core_eia860m__changelog_generators` so the table records the changes in these fields, to the extent they exist, like it records the changes in the values of other columns. 

**Describe alternatives you've considered**
We could merge these columns on from the plants table but that is not equivalent because the source is different, and IIRC, the values in the plants table have been through additional cleaning, harvesting, and conforming processes.

**Comment by zaneselvans** [comment]
It would be easy to retain `balancing_authority_code_eia` by adding it to the table schema, since it's already there in the EIA-860M dataframes. However, it's not reported at all in the first year of EIA-860M data, and it's got a lot of missing values in later years, leading to overall ~54% coverage in the final changelog table. In contrast, merging in the BA Codes associated with each plant-year results in ~94% coverage.

I'm not seeing the `sector_id_eia` or `sector_name_eia` showing up in the raw EIA-860M dataframes right now, so something else would need to be done to retain that field.  Merging it in from `out_eia__yearly_plants` also provides ~94% coverage.

**Comment by cmgosnell** [comment]
I goofed in not including these columns in the table somehow. I'm personally pretty partial to simply retaining the originally reported eia860m values. While its technically possible to merge in the canonical harvested values, that is a little off-brand for this changelog table, which is meant to capture all of the changes that exist in the originally reported 860m data.

**Comment by zaneselvans** [comment]
> If we want to fill in any gaps, that feels like it would be much more appropriate in an output table. It would be slightly more complicated to do but still pretty dang straightforward.

One unique problem with merging attributes into this table downstream is that you'll potentially end up with different records in the table than you would have had if you added those attributes before it was turned into a changelog, since those new attributes could also have changed, but in timesteps which are no longer recorded in the condensed table.

**Comment by cmgosnell** [comment]
The lower coverage is a reflection of the more spotty reporting in 860m, so I think the lower coverage here is representative of a changelog of 860m.

On the `sector_name_eia`, can we simply convert the string to the code using our standard process? That would feel consistent to me. There may be non-mapped strings in there that we would need to add. If this becomes burdensome then maybe this encoding is not worth it, but I imagine there are similar (if not more) bad strings in 860m than in the rest of eia.

**Comment by zaneselvans** [comment]
Thankfully the strings they're using for `sector_name_eia` are very clean and map perfectly to the existing IDs, so that's an easy translation to do, and will make the table compatible with all the other tables referring to this value.

You've convinced me that the changelog is a good core table, given that it contains all the information and the original table can be reconstructed from it downstream if we need/want to merge in other attributes and generate a non-eia860 changelog, and it's more than an order of magnitude smaller than the original data with all the duplicates included.

I'll leave the originally reported, low-coverage `balancing_authority_code_eia` values, and translate the `sector_name_eia` into a `sector_id_eia` for comparability with all the other tables, and we can poke @arengel to see if there's an output table that it would make sense to construct from this core data.
