### ISSUE TITLE
Review Rate Base FERC1 Table

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#3479]
Okay @jrea-rmi ! Once we merge in PR #3450, I believe we now have much cleaner detailed tables and rate base table. Can you give these a review as best you can and let me know if you find anything that seems like a red flag? I've attached the two core graphs below and here are pickled dfs of the main inputs and the rate base table itself:
- [out_ferc1__yearly_rate_base.pkl.zip](https://github.com/catalyst-cooperative/pudl/files/14650786/out_ferc1__yearly_rate_base.pkl.zip)
- [out_ferc1__detailed_balance_sheet_assets.pkl.zip](https://github.com/catalyst-cooperative/pudl/files/14650783/out_ferc1__detailed_balance_sheet_assets.pkl.zip)
- [out_ferc1__detailed_balance_sheet_liabilities.pkl.zip](https://github.com/catalyst-cooperative/pudl/files/14650784/out_ferc1__detailed_balance_sheet_liabilities.pkl.zip)
- [out_ferc1__detailed_tags.pkl.zip](https://github.com/catalyst-cooperative/pudl/files/14650785/out_ferc1__detailed_tags.pkl.zip)
- [forest_as_table_core_ferc1__yearly_balance_sheet_assets_sched110.pkl.zip](https://github.com/catalyst-cooperative/pudl/files/14650777/forest_as_table_core_ferc1__yearly_balance_sheet_assets_sched110.pkl.zip)
- [forest_as_table_core_ferc1__yearly_income_statements_sched114.pkl.zip](https://github.com/catalyst-cooperative/pudl/files/14650778/forest_as_table_core_ferc1__yearly_income_statements_sched114.pkl.zip)

<img width="648" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/d26b735d-2983-4996-a6dd-91fe8b30f280">
<img width="648" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/6eb022c7-421f-437b-bfe3-8a48d321dc0e">

### Rate base table: by input table & utility
<img width="648" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/adaf1e9e-6d2a-40f8-909b-defc4148626e">
<img width="648" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/ff65fb22-054d-47d5-aaf6-0944583f58a1">
<img width="648" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/eba6c5f0-bf08-4c81-8dde-0ea0f03233c1">
<img width="648" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/adba2d89-fb7c-43e3-b9aa-066cb034e692">
<img width="648" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/bd048eef-e206-452b-a214-f9b2d7e21152">
<img width="648" alt="image" src="https://github.com/catalyst-cooperative/pudl/assets/25487998/b1115a08-83c5-4793-8cbc-51c7899b0c6d">

I'd be happy to give you a tour of these or set you up with anything you need to best get a sense of these tables. Even high level gut reactions are vert helpful!

Once we all feel good about the contents we can move on [#3310](https://github.com/catalyst-cooperative/pudl/issues/3310)

## Compiled Found Weird Items:
 - 2004: both the assets and liabilities table are abnormally low that year.

**Comment by jrea-rmi** [comment]
This is so cool! Really exciting to have this get close to being available to everyone through PUDL!

Here are notes on what I've found so far:
- accumulated depreciation by function has mostly zero values in 2021, which then get covered up with `accumulated_depreciation_subdimension_correction`. But the real data values exist in the raw xbrl table, and it'd be good to fix that rather than using corrections.
- the accumulated depreciation table differentiates hydraulic_production_conventional and hydraulic_production_pumped_storage. But the plant in service table only gives original cost for a combined hydraulic_production. I would make `tags_aggregatable_plant_function="hydraulic_production"` for all of these. The plant_function field still differentiates the components of accumulated depreciation, but then it's easier to aggregate to a consistent technology category.
- the records from the plant in service table are missing plant_function
- xbrl_factoid `accumulated_deferred_income_taxes` should have `tags_rate_base_category==net_ADIT`
- xbrl_factoid `other_regulatory_assets` should have `tags_rate_base_category==net_regulatory_assets`
- records with `tags_rate_base_category=="other_electric_plant"` but `utility_type=="gas" or "common" or "other"` should have a different tag. Maybe other_gas_plant and other_plant? Maybe the common part should be split into components with an estimate.

The records with `utility_type ="total"` and `tags_aggregatable_utility_type=NA` have values that correspond to electric, gas, and other utility types (water, etc.). In RMI's use of this table, we would take the summary of utility plant table, calculate the fraction of assets that are electric/gas/other, and multiply all of the values for these records by that fraction to estimate the value that's included in electric/gas/other rate base. Without doing this conversion, users can only get either total rate base across all utility functions, or a partial rate base  Would you consider adding this estimated conversion of total lines into their electric/gas/other components, so users can evaluate electric/gas/other rate base?

**Comment by cmgosnell** [comment]
hey @jrea-rmi  thank you so much for these notes! Many of these have pretty straightforward fixes that I'll jump on them now.

- [ ] 2021 `accumulated_depreciation`:
    - [ ] identify fix: [#3309](https://github.com/catalyst-cooperative/pudl/issues/3309)
    - [ ] fix problem
- [ ] double hydro tags
    - [x] identify fix: this will be straightforward bc the manually compiled tags override whatever comes from the data. I can go and add  `hydraulic_production` for the accumulated depreciation table.
    - [ ] fix
- [ ] `plant_function` missing from plant in service table
    - [ ] identify fix
    - [ ] fix
- [ ] `accumulated_deferred_income_taxes` rate base tag
    - [x] identify fix: manually add this tag!
    - [ ] fix
- [ ] `other_regulatory_assets` should have `tags_rate_base_category==net_regulatory_assets`
    - [x] identify fix: manually add this tag!
    - [ ] fix
- [ ] `tags_rate_base_category=="other_electric_plant"` but `utility_type=="gas" or "common" or "other"`
    - [ ] identify fix: we set up all of the tags either use any of the 
    - [ ] fix
- [ ] total/partial records
   - [ ] identify fix: I think breaking down the total and/or partial records out into would be a great improvement! I'd love to chat with you about how y'all did this and scope it a bit before jumping in (was this ratio developed for every year/utility or for every xbrl_factoid from little slice of the detailed tree?)
   - [ ] fix (i'll probably want to break this out into its own issue and tackle it independently of these simpler fixes)

**Comment by cmgosnell** [comment]
> the records from the plant in service table are missing plant_function

@jrea-rmi do you need the main `plant_function` column to be filled? We added `tags_aggregatable_plant_function` for this table from y'all's tags so that column contains values. Is that enough or do you need the values in the main `plant_function` column - these main dimension columns come from the transformed table while the tag columns are a mix of new tags, overridden dimensions and filled in values.  you probably know this but the info about the `plant_function` is mostly embedded in the `xbrl_factoid` values but its not super consistent how it is reported across the table so we never extracted it systematically.

**Comment by cmgosnell** [comment]
> records with `tags_rate_base_category=="other_electric_plant"` but `utility_type=="gas" or "common" or "other"` should have a different tag. Maybe other_gas_plant and other_plant? Maybe the common part should be split into components with an estimate.

one more question for you @jrea-rmi ! what if this category was just `other_plant`? and you could distinguish between the utility types by the `utility_type` or `tags_aggregatable_utility_type` columns?

**Comment by jrea-rmi** [comment]
> > the records from the plant in service table are missing plant_function
> 
> @jrea-rmi do you need the main `plant_function` column to be filled? We added `tags_aggregatable_plant_function` for this table from y'all's tags and that column contains values. Is that enough or do you need the values in the main `plant_function` column - these main dimension columns come from the transformed table while the tag columns are a mix of new tags, overridden dimensions and filled in values. you probably know this but the info about the `plant_function` is mostly embedded in the `xbrl_factoid` values but its not super consistent how it is reported across the table so we never extracted it systematically.

tags_aggregatable_plant_function is fine for us. It may be confusing to users, and I could see an argument for keeping that column and dropping the main plant_function column for simplicity, but I'll know how to use it so fine for me personally.

**Comment by jrea-rmi** [comment]
> > records with `tags_rate_base_category=="other_electric_plant"` but `utility_type=="gas" or "common" or "other"` should have a different tag. Maybe other_gas_plant and other_plant? Maybe the common part should be split into components with an estimate.
> 
> one more question for you @jrea-rmi ! what if this category was just `other_plant`? and you could distinguish between the utility types by the `utility_type` or `tags_aggregatable_utility_type` columns?
> 
> but I certainly can just add a specific rate base category per `utility_type` if that is preferable

both options work for me. Maybe the single category is best; making an other_other_plant is v confusing. Also noting possible confusion with other_production_plant category, but I don't know how to get around that.

So yes, I like your idea.
