### ISSUE TITLE
clobbering data package bundles.. be better about it.

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#367]
we need to enable a user to either set a new name for a bundle of data packages or set some parameter like clobber=False to ensure they don't get rid of their existing dp's if they don't want.

**Comment by zaneselvans** [comment]
Following up on our conversation from this morning, some design issues I have:

* I think we should require the user to take some action in order to wipe out a previous ETL run, because they can represent many hours of processing (if they're doing *all* the data). This could be requiring them to set `clobber=True` or actively choosing a non-default datapackage bundle name and then re-using it (though I think that's easy to do accidentally, and so I think we'd still want to have the `clobber=False` default).
* Automatically generating a unique name for the bundle if no name is given would also work, but as you pointed out, would likely result in many bundles piling up, unless the user actively deletes them.
* While it seems convenient, hard coding a default bundle name as multiple levels within the chain of function calls has an annoying failure mode, in which people (including us) get lazy about passing the name around when we're often using the default, and then later when someone tries to use a specific name, it doesn't propagate to all the places it needs to go, and some things keep using the default.  I spent a significant amount of time untangling this kind of issue with the settings files and input/output directories. If there's going to be a default, I think it should only be injected at the highest level, and propagate throughout the function calls from there.
* Using a semi-stable default name (like the pudl distribution name and version) feels like an unhappy medium to me -- it's stable enough that folks could get used to using it, but it's not *actually* stable, and if anything is built around it, it'll break the next time they update the software, which will be confusing.

What if we had no default name in the code, but set a name in the configuration file that specifies the bundle of data packages, and set `clobber=False` by default. So folks can run it once, and get the output, and then they can either turn on clobbering, or adjust the bundle name as needed for their purposes?

**Comment by cmgosnell** [comment]
I've now removed all of the default names for the package bundle directory. From now on when anyone runs the `pudl_etl` script, they will need to include a `dp_bundle_name` (there is probably a better name for this?..). If a directory with that name already exists in 'pudl_out/datapackage' and you do not also include `--clobber`, the script will fail very early on with a message noting that the dp bundle directory already exists. (I will push all of this shortly once I get the tests all up and running).
