### ISSUE TITLE
datapkg_to_sqlite fails with duplicate data sets

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#411]
When attempting to convert a data package bundle to an SQLite database, the script will fail if the same data source appears more than once, in packages with different titles, when checking to see if the parameters are identical between them.

It seems like it should ignore this parameter since it will often (always?) be different, and has no bearing on the content of the data package.

**Comment by cmgosnell** [comment]
@zaneselvans and I just worked through this and it was failing because the data set parameters were not the same. In order to be able to flatten multiple data packages, if a data set shows up in multiple data packages, their parameters (years/tables/states) must be the same. I'm going to reword the assertion message and the settings file docs so this is more clear.
