### ISSUE TITLE
Try repeated scraping / uploading

### ISSUE THREAD

**Issue by ptvirgo** [catalyst-cooperative/pudl#547]
Make sure you can run the scraper & zenodo uploader from https://github.com/catalyst-cooperative/infrastructure, and that it works consistently.

**Comment by zaneselvans** [comment]
* Default behavior isn’t specified in the --help message for `epacems.py`. E.g. it’s unclear what happens if one doesn’t specify a state, or a month. (From running the script, it appears that the default behavior is to get all of them).
* Can lists of states / years / months be specified on the command line? Or just one at a time?
* Shouldn’t the package be `PudlScrapers`, not `PudleScrapers`? Does the InterCapping conform to Python package naming conventions?
* What do we think about using different python environment management systems in different repositories going forward? (though this package is meant to be installed locally from the repo, using `pip`, so it can be installed into an existing conda environment wherever.)
* Is there any reason not to integrate the packages in the requirements.txt directly into setup.py via the `install_requires` parameter?
* The scrapy.cfg refers to pudl.settings but where is that set? Is it just the settings in the `pudl/settings.py` module? How does it detect what things are available to be scraped (i.e. the things listed in `scrapy list`?)
* The use of the name `pudl` for this module collides with our main pudl module if you install them in the same environment. I installed the scrapers module in my `pudl-dev` environment and then everything about pudl broke.
