### ISSUE TITLE
Remove deprecated "box" arg from to_timedelta

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#549]
The `pudl.transform.epacems.py` module uses the "box" keyword argument in `to_timedelta` which has been deprecated as of pandas 1.0. Update as needed to be compatible. See also #533

**Comment by blachon** [comment]
Hi,
I came across an error that says `TypeError: to_timedelta() got an unexpected keyword argument 'box'`. From a quick read at the traceback, it looks like related to this issue.

The Traceback is enclosed. For the context, i downloaded data for eia860, eia923 and epacems for year 2017 using `pudl_data`. Data is raw and located into `pudl-work/data/`. The corresponding yaml file for `pudl_etl` is also enclosed (minimal cusomization from the example file). I saved it as `.txt` since i was not allowed to upload it as .`yaml`

I hope this helps.

[etl_example_custom.yml.txt](https://github.com/catalyst-cooperative/pudl/files/5934792/etl_example_custom.yml.txt)
[traceback_pudl.txt](https://github.com/catalyst-cooperative/pudl/files/5934784/traceback_pudl.txt)

Thanks
