### ISSUE TITLE
2019 CEMS data? 

### ISSUE THREAD

**Issue by skoeb** [catalyst-cooperative/pudl#552]
Hi there, excellent project. 

2019 CEMS data appears to be available here:
ftp://newftp.epa.gov/DMDnLoad/emissions/hourly/monthly/2019/

any reason this isn't incorporated into PUDL?

**Comment by zaneselvans** [comment]
It's because the final EIA 860 and EIA 923 data releaeses, which we process alongside CEMS, only come out in Sept/Oct of the following year, and we haven't tackled integrating year-to-date data from any of these sources yet, because they have a slightly different format, and not all of the entities are required to report monthly.

**Comment by skoeb** [comment]
Gotcha, thanks!

**Comment by zaneselvans** [comment]
But not to worry, as soon as the 2019 data is out for the eia sources we will pull in all the new CEMS data too. And we do hope to get year-to-date releases integrated at some point. It just hasn't been the highest priority yet.
