### ISSUE TITLE
make travis test work with new datastore

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#635]
Implementation detail: Right now the travis tests use data from the repo for CEMS and FERC1 (in test/data). We can remove this step and move to include the new datastore, which is ftp compatible.

**Comment by ptvirgo** [comment]
See also #634

**Comment by cmgosnell** [comment]
Thing to run/make work before pushing it up to travis:
`tox -r -v -e travis -- --fast --pudl_in=AUTO`

then it needs to pass when pushed and run on travis.

**Comment by zaneselvans** [comment]
Okay it's been a long time since we had working CI tests & documentation builds, but that's finally possible again now that the new datastore code has been merged into our sprint18 branch and the `tox` tests are (or can be) working locally (see #634)

Stuff that has to happen:
* [x] Update python version from 3.7 to 3.8 on Read The Docs
* [x] Update Read The Docs to attempt builds of relevant branches
* [x] Clean up formatting of new docstrings
* [x] Add new dependencies into setup.py
* [x] Make new PyTest classes which use the Datastore dependent on `pudl_settings_fixture`

After making those changes, I'm finding there's still an issue with getting the Datastore to do its work in the appropriate location, as is required on Travis. For local tests, we have historically wanted to be able to tell the tests to *either*
* Download a new copy of the data into a temporary location (automatically generated with the tmpdir_factory in pytest), creating a new datastore, and use that data for the tests, without touching the user's working copy of the data OR
* Use the user's existing datastore, assuming that the required data is already present, in order to avoiding downloading a potentially large amount of data to run just a short test.

For the Travis CI tests, the data must always be downloaded anew, since there's no persistent storage associated with the platform. We have used the "download new data to a temporary location" option above to do this, in combination with the `--fast` command line option which we defined for PyTest to indicate that only the most recent year's worth of data should be included in the data scope for the tests (it sets the `fast_tests` fixture to True).

The above arrangement isn't compatible with the Datastore and existing test cases as they are right now for the following reasons:
* We can't directly tell the Datastore where it should store the data at runtime, based on the dynamically generated temporary directory selected by PyTest.
* It always attempts to read the location of `PUDL_IN` from the user's `~/.pudl.yml` file, but if the environment variable `PUDL_IN` is set, it overrides the value read from the file.
* If there is no `.pudl.yml` file, Datastore creation fails, even if the `PUDL_IN` environment variable is set. And here is no `.pudl.yml` file on Travis.
* Several of the new test cases can't be limited based on the `data_scope` -- they aren't responsive to the `--fast` flag, and so attempt to download data from other years under all circumstances. This includes `TestExcelExtractor`, `TestEpaCemsDatastore`, and `TestFerc1Datastore`

There's nothing perfect about the way the tests were previously set up to run, but it seems like two pieces of functionality that are maybe worth preserving somehow are:
* Allow the tests to either download new data (exercising the datastore creation functionality) or not (to save time / bandwidth when a user is testing other aspects of the system)
* Allow the separation of the datastore test location and the user's working datastore, to avoid accidentally clobbering one.
* Allow the tests to optionally be run using only a small subset of the data (e.g. just the most recent year) so that when the tests *do* download new data (e.g. on Travis) they don't take too much time, local disk storage, or network bandwidth.

What do folks think?

**Comment by ptvirgo** [comment]
I think these priorities are inverted. You don't build software for your test environment.  You build test environments for your software.

1. Design your software to work according to it's use case.
    - in this case, pick a convention for configuration and overrides according to what user's actually expect, and stick to it.

2. Design your tests to make sure the specific functions of your software work.
    - Ideally, tests that verify that the datastore accesses data should do so.  Tests that validate end-to-end etl functionality may do that.  Tests that validate functions outside of those two scopes need to provide their own IO.

3. Design your test environment to match the expected use of the software.
    - if Travis can't deliver a test environment that covers our configuration model, then it is not the right tool to run those tests.  If it can, then it needs to be made to do so.

**Comment by ptvirgo** [comment]
(Likely) todo:


[] Datastore module takes an output directory on instantiation.
[] Datastore tests are skipped on --fast option
[] Non-datastore / end-to-end tests don't rely on datastore.

**Comment by zaneselvans** [comment]
I think one year's worth of data for an end-to-end test is more than we can check in to a repository. What's wrong with using the datastore module to obtain data for use in the end-to-end test?

**Comment by ptvirgo** [comment]
Nothing.  It specifically says using the datastore in end-to-end tests is fine.

**Comment by zaneselvans** [comment]
Oh sorry I read "Non-datastore / end-to-end tests don't rely on datastore" as indicating that the end-to-end tests should not use the datastore module.
