### ISSUE TITLE
Address parquet / pyarrow 1.0.0 vs. pandas tzinfo incompatibilites in timezone aware columns

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#705]
Something about the way that we are specifying the arrow / parquet schema in `epacems_to_parquet` appears to be incompatible with Apache Arrow 1.0.0 -- though it works fine with Arrow 0.17.1. If you attempt to run an `epacems_to_parquet` conversion with arrow 1.0.0 installed, it fails on attempting to convert the `operating_datetime_utc` column from a pandas to an arrow column.  However, if the timezone is left out of the timestamp column's schema definition (and it is allowed to assume UTC, which is the default and correct in this case) it then fails on one of the `int32` columns, saying that a floating point value has been truncated.

Not entirely clear what changed between the pre-1.0 and post-1.0 versions of Arrow that would have broken this, but that seems to be the controlling factor in whether what we're doing works or fails.

See [the Arrow 1.0.0 release announcement](https://arrow.apache.org/blog/2020/07/24/1.0.0-release/) which links to a complete change log.

To minimally recreate the bad behavior, given some pre-existing EPA CEMS datapackage outputs, you can use the following code:

```py
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

import pudl

# The path to wherever your EPA CEMS outputs are:
epacems_dir = "./"
# The path to wherever you want it to create a Parquet dataset:
output_dir = "./"
year = 2018
state = "ID"

df = (
    pd.read_csv(
        pathlib.Path(epacems_dir) / f"hourly_emissions_epacems_{year}_{state.lower()}.csv.gz",
        parse_dates=["operating_datetime_utc"],
        dtype=pudl.convert.epacems_to_parquet.create_in_dtypes()
    )
    .assign(year=year)
)
pq.write_to_dataset(
    pa.Table.from_pandas(
        df,
        preserve_index=False,
        schema=pudl.convert.epacems_to_parquet.create_cems_schema()),
    root_path=output_dir,
    partition_cols=["year", "state"],
    compression="snappy"
)
```

**Comment by zaneselvans** [comment]
Hey @karldw we ran into an issue with the recent v1.0.0 release of pyarrow, where the parquet schemas seem to have stopped working. Have you come across this by chance? Is there an easy fix? I didn't see anything that was immediately obviously related in the release notes.

**Comment by karldw** [comment]
Hmm, I hadn't run across this, but I haven't been done any work with timezones since the pyarrow 1.0 release. Could be a pyarrow bug?

I haven't read all the details, but it seems like there's a pretty active pyarrow conversation here, e.g. https://issues.apache.org/jira/browse/ARROW-9223 and https://issues.apache.org/jira/projects/ARROW/issues/ARROW-9528


Here's a simple example that doesn't require pudl outputs:

```py

import pyarrow as pa
import pandas as pd

print(pa.__version__)
# 1.0.0

df = pd.DataFrame({"time": pd.to_datetime([0, 0])})

time_field = pa.field("time",type=pa.timestamp("ms", tz="utc"), nullable=False)
schema = pa.schema([time_field])

tab = pa.Table.from_pandas(df, schema)

tab.to_pandas() 

# File ".../pandas_compat.py", line 768, in table_to_blockmanager
#   table = _add_any_metadata(table, pandas_metadata)
# File ".../pandas_compat.py", line 1167, in _add_any_metadata
#   tz = col_meta['metadata']['timezone']
# TypeError: 'NoneType' object is not subscriptable


```

(You would think `to_pandas` would be the wrong direction, but pyarrow's `write_to_parquet` calls `to_pandas` to group by the partition columns.)

**Comment by zaneselvans** [comment]
Hmm, okay breaking my original code down into smaller pieces, it turned out that this was failing in the `pa.write_to_dataset()` not the creation of the PyArrow `Table` -- and it only fails when using partition columns, so I guess that makes sense given this -- there's a column in there that has a timezone associated with it.

**Comment by zaneselvans** [comment]
PyArrow 2.0.0 is now out. We should really figure out what's going on in here...

**Comment by karldw** [comment]
I'd hoped that the issues I linked above would provide a solution, but they're resolved and the example I wrote still gives the same error.

**Comment by wesm** [comment]
Please definitely open a JIRA issue so that we can help get this resolved and appropriately unit tested

cc @nealrichardson @jorisvandenbossche

**Comment by karldw** [comment]
https://issues.apache.org/jira/browse/ARROW-10511

**Comment by jorisvandenbossche** [comment]
@karldw Thanks for opening the issue. The problem lies in some inconsistent metadata, I *think* caused by creating the Table from a pandas DataFrame with tz-naive column but schema with timezone. That is certainly a case that *should* work, but so the `to_pandas` conversion cannot deal at the moment with this inconsistent metadata. 

A temporary workaround for you could be to remove the pandas metadata from the arrow Table (of course, that can also loose other information like a column to be set as the pandas Index, but depending on your use case, you might not need this information):

```
In [5]: tab.replace_schema_metadata().to_pandas()
Out[5]: 
                       time
0 1970-01-01 00:00:00+00:00
1 1970-01-01 00:00:00+00:00
```

Will take a look at fixing it next week, unless someone else wants to give it a go.

**Comment by zaneselvans** [comment]
Hmm @karldw what's the right solution for us then? If in Parquet / Arrow the timezone information is integrated into the column metadata, but on the Pandas side it's implied (timezone naive UTC column + a column header that ends in `_utc`) or spread across more than one column (a timezone naive UTC column + another explicit timezone column with a value like `America/Los_Angeles`. Or is the only option to make sure both the Pandas and Parquet columns are either timezone naive, or timezone aware?

**Comment by zaneselvans** [comment]
@karldw Do you recall the motivation for using an explicit schema for the Arrow table in here, and the `pq.write_dataset()` function, rather than using `pandas.to_parquet()` and allowing the datatypes to be determined automatically based on the pandas column dtypes (which we're also setting explicitly). Was it just faster? Or did it have to do with specifying nullable vs. non-nullable types? And was that before the nullable extension array types were integrated into Pandas?

**Comment by karldw** [comment]
Is it possible the inferred schemas differed across CEMS state-years, because some files are all `NA` for some columns? I think I remember running into issues with conflicting schemas. This was before nullable Pandas arrays, so things could have changed.

I'm not sure what columns are best to write out. I'm fine either way on the approaches you listed.
Joris mentioned taking a look at ARROW-10511 soon, so I imagine the existing code PUDL will work again with an upcoming pyarrow release.

**Comment by wesm** [comment]
It's a good practice to enforce explicit schemas if you know what they're supposed to be

**Comment by jorisvandenbossche** [comment]
Yes, specifying explicit schemas can certainly be useful, and I would not recommend removing that (for example, when having columns with all missing data, the default inference in the pandas->arrow conversion can do the wrong thing). 

As mentioned above, you could for now remove the pandas metadata in the resulting pyarrow Table, *if* you don't need the metadata about index columns.

**Comment by zaneselvans** [comment]
I feel like I must be misunderstanding something pretty basic. The datetime column that we have in our actual application (not the minimal example @karldw create) **is timezone aware** in pandas -- it's explicitly set to UTC, and when I do `df.info()` that is reflected, so as far as I can tell there's no mismatch between the schema of the pandas dataframe, and the arrow schema. Are you saying that there's some other place within the dataframe that metadata about the timezone is stored which somehow isn't reflecting the timezone info that's stored in the column itself?

Looking at the `schema.pandas_metadata` for the `pa.Table` which is failing, I'm seeing that somehow the metadata from two different fields appears to have gotten swapped -- so the `datetime_utc` column has metadata that pertains to a categorial column (containing US state abbreviations) while the `data` field now contains the metadata that should pertain to the `datetime_utc` column, and the `state` column now has no metadata at all. And it looks like some of the data types have gotten scrambled as well:
```
{'index_columns': [],
 'column_indexes': [{'name': None,
   'field_name': None,
   'pandas_type': 'unicode',
   'numpy_type': 'object',
   'metadata': {'encoding': 'UTF-8'}}],
 'columns': [{'name': 'datetime_utc',
   'field_name': 'datetime_utc',
   'pandas_type': 'datetimetz',
   'numpy_type': 'int8',
   'metadata': {'num_categories': 49, 'ordered': False}},
  {'name': 'data',
   'field_name': 'data',
   'pandas_type': 'float64',
   'numpy_type': 'datetime64[ns]',
   'metadata': {'timezone': 'UTC'}},
  {'name': 'state',
   'field_name': 'state',
   'pandas_type': 'categorical',
   'numpy_type': 'float32',
   'metadata': None}],
 'creator': {'library': 'pyarrow', 'version': '2.0.0'},
 'pandas_version': '1.1.4'}
```

I haven't been able to create a self-contained minimal example of this yet but it does seem pretty weird. @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
Hmm, that's indeed pretty weird and buggy ... 
I was going based on the reproducible example above (https://github.com/catalyst-cooperative/pudl/issues/705#issuecomment-665283784), and there the root cause of the metadata mismatch was the data having no timezone vs the schema having a timezone. But in the end, the error you saw comes from the mismatch in the metadata, and the schema above also clearly has a mismatch (no proper timezone in the "metadata" key of the "datetime_utc" columns), although the root cause for it might be different, so I suppose that is the reason you saw the same error message for both cases. 

But so we should certainly figure out why we get such a mangled metadata for this case. If you can further try to create a reproducible example, that would certainly be helpful. But I will give it a try tomorrow as well.

**Comment by zaneselvans** [comment]
Ooookaaaaaay @jorisvandenbossche it looks like the **order** of the columns in the dataframe and the explicit schema have to be identical. Is that how it's supposed to work? I wouldn't have guessed that, given that the columns are labelled in both the dataframe and pyarrow table. I didn't see this in the documentation for `pyarrow.Table.from_pandas()` or the `pyarrow.Schema`

```py
import pyarrow as pa
import pandas as pd
import numpy as np

data_col = np.random.random_sample(2)
datetime_col = pd.date_range("2020-01-01T00:00:00Z", freq="H", periods=2)

data_field = pa.field("data_col", pa.float32(), nullable=True)
datetime_field = pa.field("datetime_utc", pa.timestamp("s", tz="UTC"), nullable=False)

df = pd.DataFrame({"datetime_utc": datetime_col, "data_col": data_col})

good_schema = pa.schema([datetime_field, data_field])
bad_schema = pa.schema([data_field, datetime_field])

good_roundtrip = pa.Table.from_pandas(df, schema=good_schema).to_pandas()
bad_roundtrip = pa.Table.from_pandas(df, schema=bad_schema).to_pandas()
```

**Comment by jorisvandenbossche** [comment]
> it looks like the order of the columns in the dataframe and the explicit schema have to be identical. Is that how it's supposed to work? 

No, that's certainly a bug (when looking only at the pandas->pyarrow conversion, it's also only the "metadata" key in the pandas metadata that has a incorrect order, the actual data columns are correctly converted). But thanks a lot for the reproducer!

**Comment by zaneselvans** [comment]
I've fixed this for now in our code by re-ordering the fields in the schema to match what we'll get from the dataframe, and
I created a separate bug on the Arrow jira with the code snippet here: https://issues.apache.org/jira/browse/ARROW-10532

**Comment by jorisvandenbossche** [comment]
Thanks for opening the issue!

I made PRs to address both bugs: https://github.com/apache/arrow/pull/8624, https://github.com/apache/arrow/pull/8625
