### ISSUE TITLE
861 failing w/o all years of data on balancing authority fixes

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/pudl#828]
found this while testing eia860m (because I accidentally used 860 years for the `test.interim_etl_test.test_interim_eia861_etl()`)

this should be easy enough to fix. this is the line that fails:

`ba.loc[BA_ID_NAME_FIXES.index, 'balancing_authority_id_eia']`

perhaps we can convert this loc statement to a merge?

**Comment by arengel** [comment]
@cmgosnell, too funny, this is exactly the bug I mentioned encountering when I tried to pull 861 data for 2005-2020.

The way I got there was by creating `PudlTabl` and then instead of asking for a specific df, I ran the 861 ETL with a non-default `Eia861Settings`. Something like this:

```python
pudl_out = PudlTabl(...)
pudl_out.etl_eia861(eia861_settings=Eia861Settings(years=sorted(range(2005, 2021)))
```

As you suggest, it goes fine up until this bit
https://github.com/catalyst-cooperative/pudl/blob/6e71bfa1a848f67ffeb1f10a161af01db75073b8/src/pudl/transform/eia861.py#L859-L861

I played around a little bit and I think replacing that with the merge below as you suggested does the trick, though I imagine there's a slicker way of doing it.

```python
df = (
    df.merge(
        BA_ID_NAME_FIXES,
        on=["report_date", "balancing_authority_name_eia", "utility_id_eia"],
        how="left",
        validate="m:1",
        suffixes=(None, "_"),
    )
    .assign(
        balancing_authority_id_eia=lambda x: x.balancing_authority_id_eia_.fillna(
            x.balancing_authority_id_eia
        )
    )
    .drop(columns=["balancing_authority_id_eia_"])
)
```

**Comment by zaneselvans** [comment]
I went ahead and merged @arengel's PR since it addresses this issue, even though it maybe doesn't improve the flexibility of the whole system much as there are inter-year and inter-table dependencies. If nothing else it'll make testing a small part of the data in development easier.
