### ISSUE TITLE
Prefect ETL

### ISSUE THREAD

**Issue by rousik** [catalyst-cooperative/pudl#840]
Master bug to track the effort to refactor pudl ETL to use prefect framework for task coordination and scheduling.

**Comment by bendnorman** [comment]
### Description
Integrate Jan's [Prefect PR](https://github.com/catalyst-cooperative/pudl/pull/901) for task orchestration and parallelization.

- [Sloan grant section](https://docs.google.com/document/d/1nz4dkBMIacITxP4ABb1JmEiWskEHUw-N/edit#heading=h.35nkun2)
- **Harvest Tag:** Sloan -> [etl] ETL Scaling and Automation

### Motivation
Using Prefect for scheduling and task coordination will allow us to parallelize portions of our ETL. This is important as we begin to load in larger datasets like EQR. Running our full ETL takes about 6 hours on our local machines. This makes it difficult to frequently run our integration and validation test which results in fewer releases. Prefect / Dask will allow us to scale our ETL as we continue to ingest more data. Prefect also provides some visual documentation of our ETL pipeline that can be helpful for new contributors. 

This project is part of infrastructure improvements aimed at more frequent releases and improved data quality. 

This epic is currently blocking the nightly builds project because nightly builds require PUDL to run relatively quickly in the cloud. 

### In Scope
- Running the ETL pipeline using Prefect and Dask locally and on a single GCP node.
- Performance goals: It would be nice to be able to run etl_fast.yml in less than 15 minutes and integration tests in less than 5 min.
- Creating performance benchmarks.

### Out of Scope
- Multi-Node ETL: In an effort to get this prefect code running as soon as possible we are going to focus on multiprocessing on a single GCP or local node. 
- Parallelizing everything. We currently don't want to refactor our entire ETL process to squeeze out every last bit of performance. We've identified some bottlenecks like loading CEMS that we want to address in this first pass.

**Comment by bendnorman** [comment]
Now that I am more familiar with the prefect code I am updating the scope. I want to merge prefect into dev as soon as possible so these two branch don't continue to diverge. The prefect branch should be able to run the full etl locally and pass all tests. Based on our conversation with Jan, running this on a Google VM might be tricky and further delay getting prefect merged into dev. 

I am also removing the integration and validation test performance goals from this epic. I will create a new epic for including validation tests within the etl run. 

## In Scope
- Run the full etl using a LocalDaskExecutor. 
- Record the ETL performance on my computer for:
   - [ ] dev at time of merge
   - [ ] prefect LocalExecutor
   - [ ] prefect LocalDaskExecutor
- Pass all integration and validation tests.
- Incorperate updated etl setting validation.

## Out of Scope
- Run on a single gcp node
- Multi-Node ETL: In an effort to get this prefect code running as soon as possible we are going to focus on multiprocessing on a single GCP or local node.
- Parallelizing everything. We currently don't want to refactor our entire ETL process to squeeze out every last bit of performance. We've identified some bottlenecks like loading CEMS that we want to address in this first pass.
- Parallelize the validation tests.

**Comment by zaneselvans** [comment]
Supplanted by the Dagster refactor. See e.g. #1960 #2104
